# Generated by Django 5.2.13 on 2026-05-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0002_rename_timestamp_challengeresult_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameplaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(max_length=50)),
                ('media_type', models.CharField(max_length=20)),
                ('target_item', models.CharField(max_length=255)),
                ('history', models.JSONField()),
                ('was_won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
