# Generated by Django 5.2.13 on 2026-05-13 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0007_airevalresult_globalboss_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='airevalresult',
            name='context',
        ),
        migrations.RemoveField(
            model_name='airevalresult',
            name='query',
        ),
        migrations.RemoveField(
            model_name='airevalresult',
            name='response',
        ),
        migrations.AddField(
            model_name='airevalresult',
            name='game_mode',
            field=models.CharField(default='classic', max_length=50),
        ),
        migrations.AddField(
            model_name='airevalresult',
            name='input_context',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='airevalresult',
            name='output_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='alternative_titles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='synopsis_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='synopsis_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='input_context',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='output_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='airevalresult',
            name='faithfulness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='airevalresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='airevalresult',
            name='precision',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='airevalresult',
            name='relevancy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bossparticipation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='challengeresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gameplaysession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='globalboss',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DuelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('media_type', models.CharField(max_length=20)),
                ('secret_title', models.CharField(max_length=255)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duels_p2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duels_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
