# Generated by Django 5.2.13 on 2026-05-16 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0013_semanticcache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeFusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_a', models.CharField(max_length=255)),
                ('title_b', models.CharField(max_length=255)),
                ('media_type_a', models.CharField(max_length=50)),
                ('media_type_b', models.CharField(max_length=50)),
                ('scenario_text', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('chaos_level', models.IntegerField(default=50)),
                ('universe_balance', models.IntegerField(default=50)),
                ('art_style', models.CharField(default='Cyberpunk', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusions', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_fusions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixes', to='animetix.creativefusion')),
            ],
        ),
    ]
