from django.urls import path

from ... import api_views

urlpatterns = [
    path(
        "fusions/",
        api_views.CreativeFusionViewSet.as_view({"get": "list", "post": "create"}),
        name="api-fusions",
    ),
    path(
        "achievements/",
        api_views.AchievementViewSet.as_view({"get": "list"}),
        name="api-achievements",
    ),
    path(
        "daily-challenge/",
        api_views.DailyChallengeDataView.as_view(),
        name="api_daily_challenge",
    ),
    path(
        "game/vs_battle/arena/", api_views.list_vs_battles, name="api_vs_battle_arena"
    ),
    path(
        "game/vs_battle/characters/",
        api_views.list_vs_characters,
        name="api_vs_battle_characters",
    ),
    path("game/vs_battle/run/", api_views.run_vs_battle, name="api_vs_battle_run"),
    path(
        "game/vs_battle/<int:battle_id>/like/",
        api_views.like_vs_battle,
        name="api_vs_battle_like",
    ),
    path(
        "game/classic/titles/",
        api_views.ClassicGameTitlesView.as_view(),
        name="api_classic_titles",
    ),
    path(
        "game/classic/state/",
        api_views.ClassicGameStateView.as_view(),
        name="api_classic_state",
    ),
    path(
        "game/classic/start/",
        api_views.ClassicGameStartView.as_view(),
        name="api_classic_start",
    ),
    path(
        "game/classic/guess/",
        api_views.ClassicGameGuessView.as_view(),
        name="api_classic_guess",
    ),
    path(
        "game/classic/reveal/",
        api_views.ClassicGameRevealView.as_view(),
        name="api_classic_reveal",
    ),
    path(
        "game/akinetix/state/",
        api_views.AkinetixGameStateView.as_view(),
        name="api_akinetix_state",
    ),
    path(
        "game/akinetix/start/",
        api_views.AkinetixGameStartView.as_view(),
        name="api_akinetix_start",
    ),
    path(
        "game/akinetix/answer/",
        api_views.AkinetixGameAnswerView.as_view(),
        name="api_akinetix_answer",
    ),
    path(
        "game/akinetix/confirm/",
        api_views.AkinetixGameConfirmView.as_view(),
        name="api_akinetix_confirm",
    ),
    path(
        "game/quiz-who/start/",
        api_views.QuiEstCeStartView.as_view(),
        name="api_quiz_who_start",
    ),
    path(
        "game/quiz-who/ask/",
        api_views.QuiEstCeAskView.as_view(),
        name="api_quiz_who_ask",
    ),
    path(
        "game/quiz-who/guess/",
        api_views.QuiEstCeGuessView.as_view(),
        name="api_quiz_who_guess",
    ),
    path(
        "game/akinetix-rl/state/",
        api_views.AkinetixRLStateView.as_view(),
        name="api_akinetix_rl_state",
    ),
    path(
        "game/akinetix-rl/start/",
        api_views.AkinetixRLStartView.as_view(),
        name="api_akinetix_rl_start",
    ),
    path(
        "game/akinetix-rl/answer/",
        api_views.AkinetixRLAnswerView.as_view(),
        name="api_akinetix_rl_answer",
    ),
    path(
        "game/animinator/ask/",
        api_views.AniminatorAskView.as_view(),
        name="api_animinator_ask",
    ),
    path(
        "game/animinator/guess/",
        api_views.AniminatorGuessView.as_view(),
        name="api_animinator_guess",
    ),
    path(
        "game/emoji/state/",
        api_views.EmojiGameStateView.as_view(),
        name="api_emoji_state",
    ),
    path(
        "game/emoji/start/",
        api_views.EmojiGameStartView.as_view(),
        name="api_emoji_start",
    ),
    path(
        "game/emoji/guess/",
        api_views.EmojiGameGuessView.as_view(),
        name="api_emoji_guess",
    ),
    path(
        "game/emoji/suggest/",
        api_views.EmojiGameSuggestView.as_view(),
        name="api_emoji_suggest",
    ),
    path(
        "game/emoji/giveup/",
        api_views.EmojiGameGiveUpView.as_view(),
        name="api_emoji_giveup",
    ),
    path(
        "game/paradox/state/",
        api_views.ParadoxGameStateView.as_view(),
        name="api_paradox_state",
    ),
    path(
        "game/paradox/start/",
        api_views.ParadoxGameStartView.as_view(),
        name="api_paradox_start",
    ),
    path(
        "game/paradox/move/",
        api_views.ParadoxGameGuessView.as_view(),
        name="api_paradox_guess",
    ),
    path(
        "game/vision/state/",
        api_views.VisionGameStateView.as_view(),
        name="api_vision_state",
    ),
    path(
        "game/vision/start/",
        api_views.VisionGameStartView.as_view(),
        name="api_vision_start",
    ),
    path(
        "game/vision/guess/",
        api_views.VisionGameGuessView.as_view(),
        name="api_vision_guess",
    ),
    path(
        "game/blindtest/state/",
        api_views.BlindtestGameStateView.as_view(),
        name="api_blindtest_state",
    ),
    path(
        "game/blindtest/start/",
        api_views.BlindtestGameStartView.as_view(),
        name="api_blindtest_start",
    ),
    path(
        "game/blindtest/guess/",
        api_views.BlindtestGameGuessView.as_view(),
        name="api_blindtest_guess",
    ),
    path(
        "game/blindtest/titles/",
        api_views.BlindtestTitlesView.as_view(),
        name="api_blindtest_titles",
    ),
    path(
        "game/covertest/titles/",
        api_views.CovertestTitlesView.as_view(),
        name="api_covertest_titles",
    ),
    path(
        "game/covertest/state/",
        api_views.CovertestGameStateView.as_view(),
        name="api_covertest_state",
    ),
    path(
        "game/covertest/reveal/",
        api_views.CovertestGameRevealView.as_view(),
        name="api_covertest_reveal",
    ),
    path(
        "game/covertest/start/",
        api_views.CovertestGameStartView.as_view(),
        name="api_covertest_start",
    ),
    path(
        "game/covertest/guess/",
        api_views.CovertestGameGuessView.as_view(),
        name="api_covertest_guess",
    ),
    path(
        "game/world-boss/active/",
        api_views.ActiveWorldBossView.as_view(),
        name="api_world_boss_active",
    ),
    path(
        "game/world-boss/question/",
        api_views.WorldBossQuestionView.as_view(),
        name="api_world_boss_question",
    ),
    path(
        "game/world-boss/answer/",
        api_views.WorldBossAnswerView.as_view(),
        name="api_world_boss_answer",
    ),
    path(
        "game/world-boss/leaderboard/",
        api_views.WorldBossLeaderboardView.as_view(),
        name="api_world_boss_leaderboard",
    ),
    path(
        "game/duel/create/",
        api_views.CreateDuelRoomView.as_view(),
        name="api_duel_create",
    ),
    path("game/duel/join/", api_views.JoinDuelRoomView.as_view(), name="api_duel_join"),
    path(
        "game/duel/matchmaking/",
        api_views.MatchmakingView.as_view(),
        name="api_duel_matchmaking",
    ),
    path(
        "game/undercover/public-rooms/",
        api_views.UndercoverPublicRoomsView.as_view(),
        name="api_undercover_public_rooms",
    ),
]
