[pytest]
DJANGO_SETTINGS_MODULE = animetix_project.test_settings
python_files = tests.py test_*.py *_tests.py
pythonpath = 
    backend
    backend/api
addopts = --reuse-db
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
