apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: worker
        image: animetix/backend:latest
        command: ["celery", "-A", "animetix_project", "worker", "--loglevel=info", "--concurrency=2"]
        envFrom:
        - secretRef:
            name: animetix-secrets
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
