apiVersion: v1
kind: Secret
metadata:
  name: animetix-secrets
type: Opaque
stringData:
  HUGGINGFACE_TOKEN: "your_hf_token_here"
  DATABASE_URL: "postgres://user:password@db-host:5432/dbname"
  REDIS_URL: "redis://redis-host:6379/1"
  DJANGO_SECRET_KEY: "your_secret_key"
