import {
  Cpu,
  Activity,
  Globe,
  Atom,
  Users,
  ShieldCheck,
  Palette,
  Headphones,
  Video,
  Cuboid,
  Brain,
  Fingerprint,
  GitBranch,
  Mic,
  Waves,
  Music,
  MessageSquare,
  Eye,
  Film,
  Binary,
  Swords,
  Map,
  Target,
  Search,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

// Static catalogue for the Singularity Labs hub. Titles/descriptions are the
// French fallbacks; the hub page overrides them at render time via
// `t('lab_hub.labs.<id>.title|desc', <fallback>)`. Icons are stored as lucide
// component references and rendered as `<lab.icon />`.
export interface LabEntry {
  id: string;
  title: string;
  desc: string;
  icon: LucideIcon;
  url: string;
  color: string;
  bg: string;
  badge: string;
  status?: string;
  catalogUrl?: string;
}

export const labs: LabEntry[] = [
  {
    id: 'quantum',
    title: 'Quantum Cognition',
    desc: "Modélisation des préférences par superposition d'états et effondrement SAT.",
    icon: Atom,
    url: '/lab/quantum/',
    color: 'text-purple-500',
    bg: 'from-purple-500/20 to-transparent',
    badge: 'Theoretical AI',
    status: 'Operational',
  },
  {
    id: 'swarm',
    title: 'Swarm Intelligence',
    desc: 'Validation décentralisée des faits de lore par consensus multi-agents IA.',
    icon: Users,
    url: '/lab/swarm/',
    color: 'text-emerald-500',
    bg: 'from-emerald-500/20 to-transparent',
    badge: 'Multi-Agent',
    status: 'Operational',
  },
  {
    id: 'plasticity',
    title: 'Synaptic Plasticity',
    desc: 'Évolution dynamique des liens sémantiques via simulation bio-inspirée.',
    icon: Activity,
    url: '/lab/synaptic/',
    color: 'text-red-500',
    bg: 'from-red-500/20 to-transparent',
    badge: 'Neural Sim',
    status: 'Operational',
  },
  {
    id: 'compiler',
    title: 'JIT Optimizer',
    desc: "Génération et injection temps-réel de microcode C optimisé par l'IA.",
    icon: Cpu,
    url: '/lab/compiler/',
    color: 'text-blue-500',
    bg: 'from-blue-500/20 to-transparent',
    badge: 'Performance',
    status: 'JIT SOTA',
  },
  {
    id: 'multiverse',
    title: 'Multiverse Genesis',
    desc: 'Génération autonome de segments de lore auto-cohérents (ADMS).',
    icon: Globe,
    url: '/lab/multiverse/',
    color: 'text-amber-500',
    bg: 'from-amber-500/20 to-transparent',
    badge: 'Generative',
    status: 'Neo4j Sync',
    catalogUrl: '/multiverse/catalog/',
  },
  {
    id: 'tot',
    title: 'Tree of Thoughts',
    desc: "Visualisez le raisonnement multi-branches (MCTS) de l'IA en temps réel.",
    icon: GitBranch,
    url: '/lab/tot/',
    color: 'text-emerald-500',
    bg: 'from-emerald-500/20 to-transparent',
    badge: 'Recursive AI',
    status: 'Operational',
  },
  {
    id: 'diagnostics',
    title: 'Neural Diagnostics',
    desc: "Analyse d'entropie et cartographie de confiance cognitive des réseaux.",
    icon: Brain,
    url: '/lab/diagnostics/',
    color: 'text-blue-500',
    bg: 'from-blue-500/20 to-transparent',
    badge: 'Diagnostics',
    status: 'Operational',
  },
  {
    id: 'liquid',
    title: 'Liquid Neural Networks',
    desc: 'Traitement adaptatif de flux continus via équations différentielles neuronales.',
    icon: Waves,
    url: '/lab/liquid-neural-networks/',
    color: 'text-cyan-400',
    bg: 'from-cyan-400/20 to-transparent',
    badge: 'Neural ODE',
    status: 'Operational',
  },
  {
    id: 'cove',
    title: 'CoVe Oracle',
    desc: 'Réduction des hallucinations via protocole Chain-of-Verification.',
    icon: ShieldCheck,
    url: '/lab/cove-oracle/',
    color: 'text-blue-400',
    bg: 'from-blue-400/20 to-transparent',
    badge: 'Reasoning',
    status: 'Operational',
  },
];

export const creativeLabs: LabEntry[] = [
  {
    id: 'manga',
    title: 'Manga Lab',
    desc: 'Rendu Manga par IA et génération de planches dynamiques.',
    icon: Palette,
    url: '/lab/manga/',
    color: 'text-blue-500',
    bg: 'from-blue-500/20 to-transparent',
    badge: 'Visual AI',
  },
  {
    id: 'manga-voice',
    title: 'Manga Voice',
    desc: 'Doublage IA zero-shot et clonage vocal pour vos personnages.',
    icon: Mic,
    url: '/lab/manga-voice/',
    color: 'text-orange-500',
    bg: 'from-orange-500/20 to-transparent',
    badge: 'Neural Dubbing',
  },
  {
    id: 'audio',
    title: 'Audio Lab',
    desc: "Clonage vocal haute fidélité et synthèse d'ambiances sonores.",
    icon: Headphones,
    url: '/lab/audio/',
    color: 'text-emerald-500',
    bg: 'from-emerald-500/20 to-transparent',
    badge: 'Neural Audio',
  },
  {
    id: 'seiyuu',
    title: 'Seiyuu Discovery',
    desc: 'Identifiez les voix iconiques et accédez au catalogue des doubleurs japonais.',
    icon: Mic,
    url: '/lab/audio/seiyuu/',
    color: 'text-emerald-400',
    bg: 'from-emerald-400/20 to-transparent',
    badge: 'VA Catalog',
  },
  {
    id: 'video',
    title: 'Video Lab',
    desc: 'Analyse et indexation vidéo intelligente par vision artificielle.',
    icon: Video,
    url: '/lab/video/',
    color: 'text-orange-500',
    bg: 'from-orange-500/20 to-transparent',
    badge: 'Computer Vision',
  },
  {
    id: 'video-rag',
    title: 'Video RAG',
    desc: 'Recherche augmentée par récupération directement sur des flux vidéo.',
    icon: Search,
    url: '/lab/video-rag/',
    color: 'text-red-500',
    bg: 'from-red-500/20 to-transparent',
    badge: 'Video Retrieval',
  },
  {
    id: 'spatial',
    title: 'Spatial Lab',
    desc: 'Reconstruction 3D et Gaussian Splatting à partir de sources 2D.',
    icon: Cuboid,
    url: '/lab/spatial/',
    color: 'text-purple-500',
    bg: 'from-purple-500/20 to-transparent',
    badge: '3D/Spatial',
  },
  {
    id: 'soundscape',
    title: 'Soundscape Lab',
    desc: "Génération procédurale d'environnements sonores immersifs et spatialisés.",
    icon: Music,
    url: '/lab/soundscape/',
    color: 'text-emerald-400',
    bg: 'from-emerald-400/20 to-transparent',
    badge: 'Generative Audio',
  },
  {
    id: 'speech-to-speech',
    title: 'Speech-to-Speech',
    desc: "Traduction vocale temps-réel préservant l'émotion et le timbre original.",
    icon: MessageSquare,
    url: '/lab/speech-to-speech/',
    color: 'text-blue-400',
    bg: 'from-blue-400/20 to-transparent',
    badge: 'Voice Conversion',
  },
  {
    id: 'voice-lab',
    title: 'Voice Lab',
    desc: 'Synthèse vocale avancée et modulation de paramètres prosodiques fins.',
    icon: Mic,
    url: '/lab/voice/',
    color: 'text-orange-400',
    bg: 'from-orange-400/20 to-transparent',
    badge: 'TTS SOTA',
  },
  {
    id: 'visual-nexus',
    title: 'Visual Nexus',
    desc: 'Interconnexion de modèles de vision pour une compréhension holistique.',
    icon: Eye,
    url: '/lab/visual-nexus/',
    color: 'text-purple-400',
    bg: 'from-purple-400/20 to-transparent',
    badge: 'Vision-Language',
  },
  {
    id: 'cinematic',
    title: 'Cinematic Reconstruction',
    desc: 'Génération de séquences cinématographiques à partir de narrations.',
    icon: Film,
    url: '/lab/cinematic/',
    color: 'text-red-400',
    bg: 'from-red-400/20 to-transparent',
    badge: 'Generative Video',
  },
];

export const cognitionLabs: LabEntry[] = [
  {
    id: 'archetype',
    title: 'Archetype Nexus',
    desc: 'Visualisez la convergence de vos traits et votre espace latent.',
    icon: Brain,
    url: '/social/archetype-nexus/',
    color: 'text-purple-500',
    bg: 'from-purple-500/20 to-transparent',
    badge: 'Social AI',
  },
  {
    id: 'memory',
    title: 'Neuro-Memory',
    desc: "Gérez l'empreinte sémantique et vos vecteurs de préférence.",
    icon: Fingerprint,
    url: '/social/neuro-memory/',
    color: 'text-emerald-500',
    bg: 'from-emerald-500/20 to-transparent',
    badge: 'Memory',
  },
  {
    id: 'simulator',
    title: 'Timeline Sim',
    desc: 'Explorez les futurs alternatifs et le regret conversationnel.',
    icon: GitBranch,
    url: '/search/counterfactual/',
    color: 'text-blue-500',
    bg: 'from-blue-500/20 to-transparent',
    badge: 'Game Theory',
  },
  {
    id: 'latent',
    title: 'Latent Space',
    desc: 'Exploration géométrique des représentations vectorielles de haute dimension.',
    icon: Binary,
    url: '/lab/latent-space/',
    color: 'text-indigo-400',
    bg: 'from-indigo-400/20 to-transparent',
    badge: 'Vector Geometry',
  },
  {
    id: 'debate',
    title: 'AI Debate Arena',
    desc: 'Confrontations sémantiques entre agents basées sur le Knowledge Graph.',
    icon: Swords,
    url: '/social/debate-arena/',
    color: 'text-red-400',
    bg: 'from-red-400/20 to-transparent',
    badge: 'Game Theory',
  },
  {
    id: 'graph-map',
    title: 'Lore World Map',
    desc: "Visualisation des clusters de connaissances détectés par l'algorithme de Leiden.",
    icon: Map,
    url: '/graph/map/',
    color: 'text-emerald-400',
    bg: 'from-emerald-400/20 to-transparent',
    badge: 'Graph RAG',
  },
  {
    id: 'strategy',
    title: 'Strategy Lab',
    desc: "Interface de simulation CFR pour l'optimisation des arbres de décision.",
    icon: Target,
    url: '/lab/strategy/',
    color: 'text-red-500',
    bg: 'from-red-500/20 to-transparent',
    badge: 'Nash Equil.',
  },
];
