# Generated by Django 5.2.14 on 2026-07-08 06:55

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, transaction

import animetix.models


def enable_vector_extension_noop(apps, schema_editor):
    """Désactivé : Extension vectorielle supprimée."""
    pass


def create_hnsw_indexes(apps, schema_editor):
    """Désactivé : La logique vectorielle a été supprimée du projet."""
    return


def drop_hnsw_indexes(apps, schema_editor):
    """Désactivé : La logique vectorielle a été supprimée du projet."""
    return


def enable_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


def _try_ddl(connection, sql, label):
    try:
        with transaction.atomic():
            with connection.cursor() as cursor:
                cursor.execute(sql)
    except Exception as e:
        print(f"Warning: {label}: {e}")


def setup_alloydb_features(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    connection = schema_editor.connection
    _try_ddl(
        connection,
        "CREATE EXTENSION IF NOT EXISTS google_ml_integration CASCADE;",
        "Could not enable google_ml_integration",
    )
    _try_ddl(
        connection,
        "CREATE EXTENSION IF NOT EXISTS alloydb_scann CASCADE;",
        "Could not enable alloydb_scann",
    )
    _try_ddl(
        connection,
        "CREATE INDEX IF NOT EXISTS animetix_vectorrecord_embedding_scann_idx "
        "ON animetix_vectorrecord USING scann (embedding cosine) "
        "WITH (num_leaves = 100);",
        "Could not create ScaNN index",
    )


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# animetix.migrations.0006_mediaitem_plot_embedding_and_more
# animetix.migrations.0010_add_hnsw_indexes
# animetix.migrations.0027_pgvector_migration
# animetix.migrations.0028_alloydb_scann_and_ml


class Migration(migrations.Migration):

    replaces = [
        ("animetix", "0001_initial"),
        ("animetix", "0002_rename_timestamp_challengeresult_completed_at_and_more"),
        ("animetix", "0003_gameplaysession"),
        ("animetix", "0004_mediaitem"),
        ("animetix", "0005_mediaitem_popularity"),
        ("animetix", "0006_mediaitem_plot_embedding_and_more"),
        ("animetix", "0007_airevalresult_globalboss_and_more"),
        (
            "animetix",
            "0008_alter_mediaitem_options_remove_airevalresult_context_and_more",
        ),
        ("animetix", "0009_gameplaysession_user"),
        ("animetix", "0010_add_hnsw_indexes"),
        ("animetix", "0011_update_embedding_dimensions"),
        ("animetix", "0012_datacurationticket_aitokenusage_golddatasetentry"),
        ("animetix", "0013_semanticcache"),
        ("animetix", "0014_creativefusion"),
        ("animetix", "0015_profile_collected_fusions"),
        ("animetix", "0016_alter_mediaitem_visual_embedding"),
        ("animetix", "0018_notification"),
        ("animetix", "0019_profile_api_key_profile_tier_latentspacepoint"),
        ("animetix", "0020_creativefusion_vn_script"),
        ("animetix", "0021_clubmembership_discoveryclub_clubmembership_club_and_more"),
        ("animetix", "0022_discoveryclub_theme_alter_clubmembership_club_and_more"),
        ("animetix", "0023_remove_mediaitem_plot_embedding_and_more"),
        (
            "animetix",
            "0024_remove_profile_api_key_profile_api_key_hash_vsbattle_and_more",
        ),
        ("animetix", "0025_profile_personalization_settings"),
        ("animetix", "0026_delete_donation_table"),
        ("animetix", "0027_pgvector_migration"),
        ("animetix", "0028_alloydb_scann_and_ml"),
        ("animetix", "0029_userrecommendation_and_more"),
        ("animetix", "0030_aitokenusage_allocated_budget_aisafetyevent"),
        ("animetix", "0031_aisafetyevent_supportticket"),
        ("animetix", "0032_golddatasetentry_entry_type_and_more"),
        ("animetix", "0033_adevent"),
        ("animetix", "0034_profile_wallet_balance_wallettransaction"),
        ("animetix", "0035_mangachapter_mangapage"),
        ("animetix", "0036_aifeedback_is_ignored_aifeedback_weight_and_more"),
        ("animetix", "0037_alter_wallettransaction_transaction_type_and_more"),
        ("animetix", "0038_remove_profile_collected_fusions_and_more"),
        ("animetix", "0039_voiceprofile"),
        ("animetix", "0040_favoritemanga"),
        ("animetix", "0041_trackerconnection"),
        ("animetix", "0042_favoritemanga_last_read_chapter_favoritemanga_status"),
        ("animetix", "0043_favoritemanga_updated_at"),
        ("animetix", "0044_quizwhoroom"),
        ("animetix", "0045_dailyresult"),
        ("animetix", "0046_delete_quizwhoroom"),
        ("animetix", "0047_globalboss_reward_distributed"),
        ("animetix", "0048_driftbaseline"),
        ("animetix", "0049_remove_profile_stripe_customer_id_and_more"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=50)),
                ("rarity", models.CharField(default="Common", max_length=20)),
                ("xp_reward", models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("media_type", models.CharField(max_length=20)),
                ("secret_title", models.CharField(max_length=255)),
                ("game_mode", models.CharField(default="classic", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp", models.IntegerField(default=0)),
                ("current_streak", models.IntegerField(default=0)),
                ("max_streak", models.IntegerField(default=0)),
                ("last_win_date", models.DateField(blank=True, null=True)),
                ("total_wins", models.IntegerField(default=0)),
                ("total_games", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("ranked_max_points", models.IntegerField(default=0)),
                ("ranked_points", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animetix.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": set(),
            },
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_type", models.CharField(max_length=50)),
                ("input_context", models.TextField()),
                ("output_text", models.TextField()),
                ("is_positive", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChallengeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempts", models.IntegerField()),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animetix.dailychallenge",
                    ),
                ),
                ("time_taken", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="GameplaySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_mode", models.CharField(max_length=50)),
                ("media_type", models.CharField(max_length=20)),
                ("target_item", models.CharField(max_length=255)),
                ("history", models.JSONField()),
                ("was_won", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=100)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("Anime", "Anime"),
                            ("Manga", "Manga"),
                            ("Character", "Character"),
                            ("Game", "Video Game"),
                            ("Actor", "Actor/Actress"),
                            ("Movie", "Movie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "title_english",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "title_native",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("popularity", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Catalog Item",
                "verbose_name_plural": "Catalog Items",
                "unique_together": {("external_id", "media_type")},
            },
        ),
        migrations.RunPython(
            code=enable_vector_extension_noop,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="plot_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="thematic_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="visual_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GlobalBoss",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("secret_title", models.CharField(max_length=255)),
                ("media_type", models.CharField(max_length=20)),
                ("total_hp", models.IntegerField(default=10000)),
                ("current_hp", models.IntegerField(default=10000)),
                ("community_hints", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("reward_xp", models.IntegerField(default=1000)),
                ("current_phase", models.IntegerField(default=1)),
                ("phase_modifiers", models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="custom_username_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="unlocked_badges",
            field=models.JSONField(default=list),
        ),
        migrations.AlterModelOptions(
            name="mediaitem",
            options={},
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="alternative_titles",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="synopsis_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="synopsis_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aifeedback",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aifeedback",
            name="input_context",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="aifeedback",
            name="output_text",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="AIREvalResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faithfulness", models.FloatField(default=0.0)),
                ("relevancy", models.FloatField(default=0.0)),
                ("precision", models.FloatField(default=0.0)),
                ("hallucination_detected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game_mode", models.CharField(default="classic", max_length=50)),
                ("input_context", models.TextField(default="")),
                ("output_text", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="BossParticipation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_contributed", models.IntegerField(default=0)),
                ("last_participation", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "boss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animetix.globalboss",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="challengeresult",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailychallenge",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("from_user", "to_user")},
            },
        ),
        migrations.AlterField(
            model_name="gameplaysession",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="DuelRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.CharField(max_length=10, unique=True)),
                ("media_type", models.CharField(max_length=20)),
                ("secret_title", models.CharField(max_length=255)),
                ("is_finished", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duels_p1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duels_p2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duels_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gameplaysession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            code=create_hnsw_indexes,
            reverse_code=drop_hnsw_indexes,
        ),
        migrations.CreateModel(
            name="DataCurationTicket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_title", models.CharField(max_length=255)),
                ("issue_description", models.TextField()),
                ("source_pg", models.JSONField(default=dict)),
                ("source_neo4j", models.JSONField(default=dict)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AITokenUsage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine", models.CharField(max_length=50)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("cost_estimate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoldDatasetEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.TextField()),
                ("instruction", models.TextField()),
                ("response", models.TextField()),
                ("is_validated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_feedback",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="animetix.aifeedback",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreativeFusion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_a", models.CharField(max_length=255)),
                ("title_b", models.CharField(max_length=255)),
                ("media_type_a", models.CharField(max_length=50)),
                ("media_type_b", models.CharField(max_length=50)),
                ("scenario_text", models.TextField()),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("chaos_level", models.IntegerField(default=50)),
                ("universe_balance", models.IntegerField(default=50)),
                ("art_style", models.CharField(default="Cyberpunk", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fusions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_fusions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remixes",
                        to="animetix.creativefusion",
                    ),
                ),
                ("vn_script", models.JSONField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="collected_fusions",
            field=models.ManyToManyField(
                blank=True,
                related_name="collected_by_profiles",
                to="animetix.creativefusion",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("achievement", "Succès Débloqué"),
                            ("duel", "Défi / Duel"),
                            ("social", "Interaction Sociale"),
                            ("system", "Système"),
                            ("info", "Information"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("premium", "Premium"),
                    ("pro", "Professional"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LatentSpacePoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_type", models.CharField(max_length=20)),
                ("vibe_type", models.CharField(max_length=20)),
                ("external_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("z", models.FloatField()),
                ("cluster", models.IntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["media_type", "vibe_type"],
                        name="animetix_la_media_t_69117f_idx",
                    )
                ],
                "unique_together": {("media_type", "vibe_type", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="ClubMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Membre"),
                            ("admin", "Administrateur"),
                            ("owner", "Propriétaire"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscoveryClub",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_clubs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="joined_clubs",
                        through="animetix.ClubMembership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("theme", models.CharField(default="General", max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="clubmembership",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="animetix.discoveryclub"
            ),
        ),
        migrations.CreateModel(
            name="ClubEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("event_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="animetix.discoveryclub",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="clubmembership",
            unique_together={("user", "club")},
        ),
        migrations.AlterField(
            model_name="clubmembership",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="animetix.discoveryclub",
            ),
        ),
        migrations.AlterField(
            model_name="clubmembership",
            name="role",
            field=models.CharField(
                choices=[("Member", "Member"), ("Officer", "Officer")],
                default="Member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="clubmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="mediaitem",
            name="plot_embedding",
        ),
        migrations.RemoveField(
            model_name="mediaitem",
            name="thematic_embedding",
        ),
        migrations.RemoveField(
            model_name="mediaitem",
            name="visual_embedding",
        ),
        migrations.CreateModel(
            name="SemanticCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField(unique=True)),
                ("response_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="api_key_hash",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="VsBattle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_a_name", models.CharField(max_length=255)),
                ("char_b_name", models.CharField(max_length=255)),
                (
                    "char_a_franchise",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "char_b_franchise",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("char_a_data", models.JSONField()),
                ("char_b_data", models.JSONField()),
                ("winner", models.CharField(max_length=255)),
                ("verdict_summary", models.TextField()),
                ("debate_history", models.JSONField()),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vs_battles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_vs_battles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchetypeDriftSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archetype_id", models.CharField(max_length=100)),
                ("intensity", models.FloatField()),
                ("shonen_affinity", models.FloatField()),
                ("seinen_affinity", models.FloatField()),
                ("logic_consistency", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archetype_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="animetix_ar_user_id_6d39fd_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="personalization_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS animetix_donation;",
            reverse_sql="",
        ),
        migrations.RunPython(
            code=enable_vector_extension,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name="VectorRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(db_index=True, max_length=100)),
                ("item_id", models.CharField(db_index=True, max_length=100)),
                ("embedding", animetix.models.PGVectorField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("document", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["collection_name", "item_id"],
                        name="animetix_ve_collect_20560a_idx",
                    )
                ],
                "unique_together": {("collection_name", "item_id")},
            },
        ),
        migrations.RunPython(
            code=setup_alloydb_features,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name="UserRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("rank", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.RenameIndex(
            model_name="vectorrecord",
            new_name="animetix_ve_collect_7406aa_idx",
            old_name="animetix_ve_collect_20560a_idx",
        ),
        migrations.AddField(
            model_name="clubevent",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="event_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vectorrecord",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="userrecommendation",
            name="media_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="animetix.mediaitem"
            ),
        ),
        migrations.AddField(
            model_name="userrecommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrecommendation",
            unique_together={("user", "media_item")},
        ),
        migrations.AddField(
            model_name="aitokenusage",
            name="allocated_budget",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AISafetyEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("input", "Entrée Utilisateur"),
                            ("output", "Sortie Assistant"),
                            ("system", "Système"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("block", "Bloqué"),
                            ("warn", "Avertissement"),
                            ("rewrite", "Réécriture"),
                            ("none", "Aucune"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detected_categories", models.JSONField(default=list)),
                ("input_text", models.TextField(blank=True, null=True)),
                ("output_text", models.TextField(blank=True, null=True)),
                ("reasoning", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("query", models.TextField()),
                ("ai_response", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("resolved", "Résolu"),
                            ("closed", "Fermé"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("feedback_score", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="golddatasetentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("QA", "Question-Answering"),
                    ("MULTIVERSE", "Synthetic Universe"),
                    ("DISTILLATION", "Model Distillation"),
                    ("OTHER", "Other Synthetic Data"),
                ],
                default="QA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="golddatasetentry",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="AdEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("impression", "Impression"), ("click", "Click")],
                        max_length=20,
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[("video", "Video"), ("banner", "Banner")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="wallet_balance",
            field=models.IntegerField(default=1000),
        ),
        migrations.CreateModel(
            name="MangaChapter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.FloatField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manga",
                    models.ForeignKey(
                        limit_choices_to={"media_type": "Manga"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="animetix.mediaitem",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("manga", "number")},
            },
        ),
        migrations.CreateModel(
            name="MangaPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("image_url", models.URLField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="animetix.mangachapter",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("chapter", "number")},
            },
        ),
        migrations.AddField(
            model_name="aifeedback",
            name="is_ignored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aifeedback",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="golddatasetentry",
            name="ai_critique",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="golddatasetentry",
            name="ai_validation_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="golddatasetentry",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="golddatasetentry",
            name="is_safe",
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="collected_fusions",
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ad_passive", "Passive Mining"),
                            ("ad_active", "Rewarded Video"),
                            ("purchase", "Direct Purchase"),
                            ("ai_usage", "AI Consumption"),
                            ("daily_grant", "Daily Grant"),
                            ("welcome_bonus", "Welcome Bonus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("japanese", "Japanese (Seiyuu)"),
                            ("french", "French (Doubleur)"),
                            ("other", "Other"),
                        ],
                        default="japanese",
                        max_length=20,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("dataset", "Dataset (Hugging Face)"),
                            ("youtube", "YouTube Ingestion"),
                            ("upload", "Manual Upload"),
                        ],
                        default="dataset",
                        max_length=20,
                    ),
                ),
                ("definition", models.TextField(blank=True, null=True)),
                ("roles", models.TextField(blank=True, null=True)),
                ("impact", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "origin_detail",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "sample_file",
                    models.FileField(blank=True, null=True, upload_to="audio/samples/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrackerConnection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracker",
                    models.CharField(
                        choices=[
                            ("myanimelist", "MyAnimeList"),
                            ("anilist", "AniList"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token", models.TextField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracker_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tracker")},
            },
        ),
        migrations.CreateModel(
            name="FavoriteManga",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manga",
                    models.ForeignKey(
                        limit_choices_to={"media_type": "Manga"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="animetix.mediaitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_mangas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("last_read_chapter", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reading", "Reading"),
                            ("completed", "Completed"),
                            ("plan_to_read", "Plan to Read"),
                        ],
                        default="reading",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("user", "manga")},
            },
        ),
        migrations.CreateModel(
            name="DailyResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("media_type", models.CharField(max_length=20)),
                ("score", models.IntegerField(default=0)),
                ("attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date", "media_type")},
            },
        ),
        migrations.AddField(
            model_name="globalboss",
            name="reward_distributed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DriftBaseline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=50, unique=True)),
                ("norms", models.JSONField(default=list)),
                ("sample_size", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
