# Generated by Django 5.2.13 on 2026-05-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animetix", "0003_gameplaysession"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=100)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("Anime", "Anime"),
                            ("Manga", "Manga"),
                            ("Character", "Character"),
                            ("Game", "Video Game"),
                            ("Actor", "Actor/Actress"),
                            ("Movie", "Movie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "title_english",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "title_native",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catalog Item",
                "verbose_name_plural": "Catalog Items",
                "unique_together": {("external_id", "media_type")},
            },
        ),
    ]
