# Generated by Django 5.2.13 on 2026-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0004_mediaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
    ]
