# Generated by Django 5.2.13 on 2026-05-12 20:15

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


def enable_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")

class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0005_mediaitem_popularity'),
    ]

    operations = [
        migrations.RunPython(enable_vector_extension, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='mediaitem',
            name='plot_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='thematic_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='visual_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
