# Generated by Django 5.2.13 on 2026-05-12 20:15

from django.db import migrations, models

def enable_vector_extension(apps, schema_editor):
    """Désactivé : Extension vectorielle supprimée."""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0005_mediaitem_popularity'),
    ]

    operations = [
        migrations.RunPython(enable_vector_extension, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='mediaitem',
            name='plot_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='thematic_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='visual_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
