# Generated by Django 5.2.13 on 2026-05-15 17:29

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0012_datacurationticket_aitokenusage_golddatasetentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(unique=True)),
                ('response_text', models.TextField()),
                ('query_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
