# Generated by Django 5.2.13 on 2026-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0014_creativefusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='collected_fusions',
            field=models.ManyToManyField(blank=True, related_name='collected_by_profiles', to='animetix.creativefusion'),
        ),
    ]
