# Generated by Django 5.2.13 on 2026-05-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0015_profile_collected_fusions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='visual_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
