# Generated by Django 5.2.13 on 2026-05-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animetix", "0019_profile_api_key_profile_tier_latentspacepoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="creativefusion",
            name="vn_script",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
