# Generated by Django 5.2.13 on 2026-05-31 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animetix", "0023_remove_mediaitem_plot_embedding_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="api_key",
        ),
        migrations.AddField(
            model_name="profile",
            name="api_key_hash",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="VsBattle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_a_name", models.CharField(max_length=255)),
                ("char_b_name", models.CharField(max_length=255)),
                (
                    "char_a_franchise",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "char_b_franchise",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("char_a_data", models.JSONField()),
                ("char_b_data", models.JSONField()),
                ("winner", models.CharField(max_length=255)),
                ("verdict_summary", models.TextField()),
                ("debate_history", models.JSONField()),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vs_battles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_vs_battles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchetypeDriftSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archetype_id", models.CharField(max_length=100)),
                ("intensity", models.FloatField()),
                ("shonen_affinity", models.FloatField()),
                ("seinen_affinity", models.FloatField()),
                ("logic_consistency", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archetype_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="animetix_ar_user_id_6d39fd_idx",
                    )
                ],
            },
        ),
    ]
