# Generated by Django 5.2.13 on 2026-06-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "animetix",
            "0024_remove_profile_api_key_profile_api_key_hash_vsbattle_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="personalization_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
