# Generated by Django 5.2.13 on 2026-06-06 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0029_userrecommendation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aitokenusage',
            name='allocated_budget',
            field=models.IntegerField(default=0),
        ),
    ]
