# Generated by Django 5.2.13 on 2026-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0031_aisafetyevent_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='golddatasetentry',
            name='entry_type',
            field=models.CharField(choices=[('QA', 'Question-Answering'), ('MULTIVERSE', 'Synthetic Universe'), ('DISTILLATION', 'Model Distillation'), ('OTHER', 'Other Synthetic Data')], default='QA', max_length=20),
        ),
        migrations.AddField(
            model_name='golddatasetentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
