# Generated by Django 5.2.13 on 2026-06-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0032_golddatasetentry_entry_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], max_length=20)),
                ('ad_type', models.CharField(choices=[('video', 'Video'), ('banner', 'Banner')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
