# Generated by Django 5.2.14 on 2026-06-13 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetix', '0034_profile_wallet_balance_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(limit_choices_to={'media_type': 'Manga'}, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='animetix.mediaitem')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('manga', 'number')},
            },
        ),
        migrations.CreateModel(
            name='MangaPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('image_url', models.URLField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='animetix.mangachapter')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('chapter', 'number')},
            },
        ),
    ]
