# Generated by Django 5.2.14 on 2026-06-19 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0036_aifeedback_is_ignored_aifeedback_weight_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("ad_passive", "Passive Mining"),
                    ("ad_active", "Rewarded Video"),
                    ("purchase", "Direct Purchase"),
                    ("ai_usage", "AI Consumption"),
                    ("daily_grant", "Daily Grant"),
                    ("welcome_bonus", "Welcome Bonus"),
                    ("market_sale", "Market Sale"),
                    ("market_purchase", "Market Purchase"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MarketListing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fusion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="animetix.creativefusion",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
