# Generated by Django 5.2.14 on 2026-06-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0038_remove_profile_collected_fusions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("japanese", "Japanese (Seiyuu)"),
                            ("french", "French (Doubleur)"),
                            ("other", "Other"),
                        ],
                        default="japanese",
                        max_length=20,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("dataset", "Dataset (Hugging Face)"),
                            ("youtube", "YouTube Ingestion"),
                            ("upload", "Manual Upload"),
                        ],
                        default="dataset",
                        max_length=20,
                    ),
                ),
                ("definition", models.TextField(blank=True, null=True)),
                ("roles", models.TextField(blank=True, null=True)),
                ("impact", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "origin_detail",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "sample_file",
                    models.FileField(blank=True, null=True, upload_to="audio/samples/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
