# Generated by Django 5.2.14 on 2026-06-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0041_trackerconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritemanga",
            name="last_read_chapter",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="favoritemanga",
            name="status",
            field=models.CharField(
                choices=[
                    ("reading", "Reading"),
                    ("completed", "Completed"),
                    ("plan_to_read", "Plan to Read"),
                ],
                default="reading",
                max_length=20,
            ),
        ),
    ]
