# Generated by Django 5.2.14 on 2026-06-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0042_favoritemanga_last_read_chapter_favoritemanga_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritemanga",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
