# Generated by Django 5.2.14 on 2026-06-29 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0043_favoritemanga_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizWhoRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.CharField(max_length=10, unique=True)),
                ("media_type", models.CharField(default="Anime", max_length=20)),
                ("difficulty", models.CharField(default="Normal", max_length=20)),
                ("board", models.JSONField(default=list)),
                ("questions", models.JSONField(default=list)),
                ("secret1", models.CharField(blank=True, max_length=64)),
                ("secret2", models.CharField(blank=True, max_length=64)),
                ("turn", models.IntegerField(default=1)),
                ("eliminated1", models.JSONField(default=list)),
                ("eliminated2", models.JSONField(default=list)),
                ("last_answer", models.JSONField(blank=True, default=dict)),
                ("winner", models.IntegerField(blank=True, null=True)),
                ("is_finished", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizwho_p1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizwho_p2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
