# Generated by Django 5.2.14 on 2026-07-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0045_dailyresult"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuizWhoRoom",
        ),
    ]
