# Generated by Django 5.2.14 on 2026-07-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0046_delete_quizwhoroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalboss",
            name="reward_distributed",
            field=models.BooleanField(default=False),
        ),
    ]
