# Generated by Django 5.2.14 on 2026-07-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0047_globalboss_reward_distributed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriftBaseline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=50, unique=True)),
                ("norms", models.JSONField(default=list)),
                ("sample_size", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
