# Generated by Django 5.2.14 on 2026-07-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0048_driftbaseline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stripe_subscription_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stripe_subscription_item_id",
        ),
    ]
