# Generated by Django 5.2.14 on 2026-07-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0001_squashed_0049_remove_profile_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="ON : les visiteurs voient la page de maintenance ; le staff navigue normalement.",
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Message optionnel affiché sur la page de maintenance.",
                    ),
                ),
                (
                    "maintenance_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Heure de retour estimée (informatif, affiché sur la page).",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration du site",
                "verbose_name_plural": "Configuration du site",
            },
        ),
    ]
