# Generated by Django 5.2.14 on 2026-07-12 10:09

from django.db import migrations, models
from django.utils import timezone


def retire_the_legacy_raid(apps, schema_editor):
    """End every boss spawned under the guess-the-title rules.

    Their 10 000 HP was sized for 100-damage attacks. Left alive, the first
    tier-12 answer of the new quiz would take a fifth of the boss.

    The weekly-spawn guard (see api/games/world_boss.py) skips spawning a
    fresh boss whenever a row with a future end_date exists -- it does not
    check is_active. A retired boss keeps an end_date up to 7 days out, so
    setting is_active=False alone would still block the respawn: the game
    would have no boss to fight until that old date elapsed. Both fields
    must move together: is_active=False retires it, and end_date=now expires
    it, so the guard's `.exists()` check no longer sees it and a fresh
    100 000 HP raid spawns on the next request.
    """
    GlobalBoss = apps.get_model("animetix", "GlobalBoss")
    GlobalBoss.objects.filter(total_hp__lt=100000).update(
        is_active=False, end_date=timezone.now()
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0050_siteconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="bossparticipation",
            name="best_tier",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="limiter_breaks",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(retire_the_legacy_raid, noop),
    ]
