# Generated by Django 5.2.14 on 2026-07-12 10:09

from django.db import migrations, models


def retire_the_legacy_raid(apps, schema_editor):
    """End every boss spawned under the guess-the-title rules.

    Their 10 000 HP was sized for 100-damage attacks. Left alive, the first
    tier-12 answer of the new quiz would take a fifth of the boss. The weekly
    spawn puts a fresh 100 000 HP raid in place on the next request.
    """
    GlobalBoss = apps.get_model("animetix", "GlobalBoss")
    GlobalBoss.objects.filter(total_hp__lt=100000).update(is_active=False)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0050_siteconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="bossparticipation",
            name="best_tier",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="limiter_breaks",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(retire_the_legacy_raid, noop),
    ]
