# Generated by Django 5.2.14 on 2026-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0051_bossparticipation_best_tier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bossparticipation",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="limiter_break",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="pending_archetype",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="pending_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="pending_index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="pending_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="pending_options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="pending_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="pending_subject",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="run_damage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bossparticipation",
            name="tier",
            field=models.IntegerField(default=1),
        ),
    ]
