# Generated by Django 5.2.14 on 2026-07-12 11:02

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def deduplicate_boss_participations(apps, schema_editor):
    """Fold every duplicate (user, boss) pair into a single row before the
    uniqueness constraint below is enforced.

    The lock in world_boss.py ("the rowcount is the lock") only holds if there
    is exactly one BossParticipation row per (user, boss). A double-fired
    client, React StrictMode, or a retried request can race get_or_create() on
    a brand-new pair -- both miss the get(), both INSERT -- leaving two rows
    behind. Applying the constraint below on top of that would simply fail to
    migrate, so duplicates are folded first: the row with the most
    points_contributed survives (ties broken by the lowest pk), the others'
    points_contributed are folded into it, best_tier keeps the highest of the
    two, limiter_breaks is summed, and the rest are deleted.
    """
    BossParticipation = apps.get_model("animetix", "BossParticipation")

    duplicate_pairs = (
        BossParticipation.objects.values("user_id", "boss_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for pair in duplicate_pairs:
        rows = list(
            BossParticipation.objects.filter(
                user_id=pair["user_id"], boss_id=pair["boss_id"]
            ).order_by("-points_contributed", "pk")
        )
        keeper, *others = rows
        keeper.points_contributed += sum(row.points_contributed for row in others)
        keeper.best_tier = max([keeper.best_tier] + [row.best_tier for row in others])
        keeper.limiter_breaks += sum(row.limiter_breaks for row in others)
        keeper.save(update_fields=["points_contributed", "best_tier", "limiter_breaks"])
        BossParticipation.objects.filter(pk__in=[row.pk for row in others]).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0052_bossparticipation_issued_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_boss_participations, noop),
        migrations.AddConstraint(
            model_name="bossparticipation",
            constraint=models.UniqueConstraint(
                fields=("user", "boss"), name="unique_bossparticipation_user_boss"
            ),
        ),
    ]
