# Generated by Django 5.2.14 on 2026-07-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0054_globalboss_week_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="MangaCover",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manga_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "mangadex_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("covers", models.JSONField(default=dict)),
                (
                    "title_english",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "title_native",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("synonyms", models.JSONField(blank=True, default=list, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Manga Cover",
                "verbose_name_plural": "Manga Covers",
            },
        ),
    ]
