# Generated by Django 5.2.14 on 2026-07-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0055_mangacover"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.FileField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
