# Generated by Django 5.2.14 on 2026-08-01 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animetix", "0057_mangareadingprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MangaTrackerLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracker",
                    models.CharField(
                        choices=[
                            ("myanimelist", "MyAnimeList"),
                            ("anilist", "AniList"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remote_id", models.CharField(max_length=50)),
                ("remote_title", models.CharField(blank=True, max_length=255)),
                ("remote_progress", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("confirmed", "Confirmed"),
                        ],
                        default="suggested",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manga",
                    models.ForeignKey(
                        limit_choices_to={"media_type": "Manga"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracker_links",
                        to="animetix.mediaitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracker_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "manga", "tracker")},
            },
        ),
    ]
