import pytest
from unittest.mock import MagicMock, patch
import os
import json
from animetix.models import AIFeedback
from django.contrib.auth.models import User

@pytest.mark.django_db
def test_rlhf_loop_integration(mock_container):
    """
    Integration test for the Swarm-to-DPO self-improving loop.
    Verifies that negative feedback triggers Swarm curation and generates a DPO pair.
    """
    # 1. Setup Mock Container
    # mock_container is provided by conftest.py (it's the mock_container_instance)
    mock_container.agentic_rag = MagicMock()
    mock_container.agentic_rag.return_value.plan_and_solve.return_value = "This is a Perfect Answer generated by Swarm/Thinking mode."
    mock_container.agentic_rag.plan_and_solve.return_value = "This is a Perfect Answer generated by Swarm/Thinking mode."
    
    # Ensure prompt_manager exists and returns a valid prompt template for DPO
    mock_container.prompt_manager = MagicMock()
    def mock_get_prompt(key, **kwargs):
        # Emulate real PromptManager formatting
        template = "Context: {context}\nResponse:"
        return template.format(**kwargs), ""
    mock_container.prompt_manager.return_value.get_prompt.side_effect = mock_get_prompt
    mock_container.prompt_manager.get_prompt.side_effect = mock_get_prompt
    
    # 2. Create a User and a Negative Feedback entry
    user = User.objects.create_user(username="test_rlhf_user", password="password123")
    
    # Validation in DPOFeedbackLoop requires:
    # - context length >= 5
    # - output length >= 15
    # - no generic error keywords
    feedback = AIFeedback.objects.create(
        user=user,
        feedback_type="rag_error",
        input_context="Who is the protagonist of 'Monster'?",
        output_text="I think it's someone named Naruto, but I'm not sure.", # Incorrect and long enough
        is_positive=False
    )
    
    # 3. Define output path (matching the script's logic)
    script_dir = os.path.dirname(os.path.abspath(__file__)) # tests/core
    project_root = os.path.dirname(os.path.dirname(script_dir)) # Project root
    output_path = os.path.join(project_root, "data", "mlops", "datasets", "dpo_train_swarm.jsonl")
    
    # Ensure clean state
    if os.path.exists(output_path):
        os.remove(output_path)
        
    # 4. Run the curation logic
    try:
        with patch('scripts.curate_dpo_dataset.get_container', return_value=mock_container):
            from scripts.curate_dpo_dataset import curate_dpo_dataset
            curate_dpo_dataset()
            
            # 5. Verify the results
            assert os.path.exists(output_path), f"Output file not found at {output_path}"
            
            with open(output_path, 'r', encoding='utf-8') as f:
                lines = f.readlines()
                assert len(lines) == 1, f"Expected 1 DPO pair, found {len(lines)}"
                
                entry = json.loads(lines[0])
                assert "prompt" in entry
                assert entry["chosen"] == "This is a Perfect Answer generated by Swarm/Thinking mode."
                assert entry["rejected"] == feedback.output_text
                assert feedback.input_context in entry["prompt"]
    finally:
        # 6. Cleanup
        if os.path.exists(output_path):
            os.remove(output_path)
