[supervisord]
nodaemon=true
;user=root
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:django]
# Migration + Collectstatic + Lancement Gunicorn depuis le bon dossier backend/api
command=bash -c "for i in 1 2 3 4 5; do python manage.py migrate && break || sleep 3; done && python manage.py collectstatic --noinput && gunicorn animetix_project.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:7860 --workers 2"
directory=/app/backend/api
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery_worker]
# Attente de la DB avant lancement (lancé depuis backend/api pour trouver le module animetix_project)
command=bash -c "sleep 5 && celery -A animetix_project worker --loglevel=info --concurrency=2"
directory=/app/backend/api
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0



