import { useTranslation } from 'react-i18next';

export const useGameModes = () => {
  const { i18n } = useTranslation();
  const isEn = i18n.language.startsWith('en');

  const modesSolo = [
    {
      titre: 'Akinetix',
      titre_brush_1: 'AKINETIX',
      titre_brush_2: isEn ? 'THE SEER' : 'LE DEVIN',
      description: isEn
        ? 'Two modes: let the AI guess what you have in mind, or quiz the genie yourself. Anime, manga or character.'
        : "Deux modes : laisse l'IA deviner, ou interroge toi-même le génie. Anime, manga ou personnage.",
      icon_url: '/static/img/modes/akinetix.png',
      gradient: 'from-amber-400 to-orange-600 dark:from-amber-500/80 dark:to-orange-700/80',
      url: '/akinetix/',
    },
    {
      titre: 'Classic',
      titre_brush_1: 'ANIMETIX',
      titre_brush_2: 'CLASSIQUE',
      description: isEn
        ? 'Hunt the mystery work — each guess tells you how close you are.'
        : "Traquez l'œuvre mystère : chaque tentative vous dit si vous brûlez.",
      icon_url: '/static/img/modes/classic.png',
      gradient: 'from-blue-400 to-indigo-600 dark:from-blue-500/80 dark:to-indigo-700/80',
      url: '/game/classic/',
    },
    {
      titre: 'Paradox',
      titre_brush_1: 'PARADOX',
      titre_brush_2: isEn ? 'THE ODD ONE' : "L'INTRUS",
      description: isEn 
        ? 'Identify the odd one out or temporal paradox generated by the AI.' 
        : "Identifiez l'intrus ou le paradoxe temporel parmi les propositions de l'IA.",
      icon_url: '/static/img/modes/paradox.png',
      gradient: 'from-purple-400 to-pink-600 dark:from-purple-500/80 dark:to-pink-700/80',
      url: '/paradox/',
    },
    {
      titre: 'Emoji',
      titre_brush_1: 'EMOJI QUEST',
      titre_brush_2: isEn ? 'DECODING' : 'DÉCRYPTAGE',
      description: isEn 
        ? 'Decode anime and manga titles hidden behind combinations of emojis.' 
        : "Décodez les titres d'anime et de manga cachés derrière des combinaisons d'emojis.",
      icon_url: '/static/img/modes/emoji.png',
      gradient: 'from-emerald-400 to-teal-600 dark:from-emerald-500/80 dark:to-teal-700/80',
      url: '/emoji/',
    },
    {
      titre: 'Covertest',
      titre_brush_1: 'COVER QUEST',
      titre_brush_2: isEn ? 'THE PUZZLE' : 'LE CASSE-TÊTE',
      description: isEn 
        ? 'Rebuild blurry or scrambled manga covers generated by the AI.' 
        : "Reconnaissez les couvertures de mangas floutées ou mélangées par l'IA.",
      icon_url: '/static/img/modes/covertest.png',
      gradient: 'from-rose-400 to-red-600 dark:from-rose-500/80 dark:to-red-700/80',
      url: '/covertest/',
    },
    {
      titre: 'Blindtest',
      titre_brush_1: 'ANIME',
      titre_brush_2: 'BLINDTEST',
      description: isEn 
        ? 'Recognize legendary OSTs transformed or filtered by AI.' 
        : "Reconnaissez les OST mythiques transformées ou filtrées par l'IA.",
      icon_url: '/static/img/modes/blindTest.png',
      gradient: 'from-emerald-400 to-green-600 dark:from-emerald-500/80 dark:to-green-700/80',
      url: '/blindtest/',
    },
    {
      titre: 'VsBattle',
      titre_brush_1: 'ARENA',
      titre_brush_2: isEn ? 'ULTIMATUM' : 'ULTIMATUM',
      description: isEn 
        ? 'Trans-dimensional duels moderated by AI.' 
        : "Duels trans-dimensionnels arbitrés par l'IA.",
      icon_url: '/static/img/modes/VSBattle.png',
      gradient: 'from-red-500 to-red-900 dark:from-red-600/80 dark:to-red-950/80',
      url: '/game/vsbattle/',
    }
    ];

    const modesMulti = [
    {
      titre: 'Undercover',
      description: isEn 
        ? 'Unmask the intruder among your friends in a secret word match.' 
        : 'Démasquez l\'intrus parmi vos amis dans une partie de mots infiltrés.',
      icon_url: '/static/img/modes/undercover.png',
      url: '/game/duel/lobby/',
    },
    {
      titre: 'Code Manga',
      description: isEn 
        ? 'Make your team guess anime/manga cards with the minimum amount of words.' 
        : 'Faites deviner des cartes d\'anime/manga avec le moins d\'indices possibles.',
      icon_url: '/static/img/modes/codemanga.png',
      url: '/game/duel/lobby/',
    }
    ];

    const modesCreative = [
    {
      titre: isEn ? 'CREATIVE FORGE' : 'FORGE CRÉATIVE',
      titre_sub: isEn ? 'ACCESS THE AI MEDIA LABORATORIES' : 'ACCÉDEZ AUX LABORATOIRES DE MÉDIAS IA',
      fusion_image: '/static/img/modes/fusion.png',
      url: '/lab/forge-hub/',
    }
    ];

    const modesLab = [
    {
      titre: 'Latent Space',
      url: '/lab/latent-space/',
    },
    {
      titre: 'Theater',
      url: '/theater/',
    }
    ];

    return { modesSolo, modesMulti, modesCreative, modesLab, isEn };
    };