"""Precompute which characters have a VS Battles Wiki sheet.

Walks the character catalogue in popularity order (so the most important
characters are always covered) and, for each one, checks whether a matching
page exists on VS Battles Wiki. Characters found get an "official" sheet
source; those not found are flagged "synthetic" — their sheet is generated by
the AI at battle time — so no important fighter is ever dropped from the roster.

The result is stored on ``MediaItem.metadata['vsbattle']`` and consumed by the
Arena roster endpoint (``game/vs_battle/characters/``).

Usage:
    python manage.py precompute_vsbattle_sheets --limit 1000
    python manage.py precompute_vsbattle_sheets --limit 1500 --force
"""

import re
import time

from core.utils.security import safe_http_request
from django.core.management.base import BaseCommand
from django.db.models import F, IntegerField
from django.db.models.fields.json import KeyTextTransform, KeyTransform
from django.db.models.functions import Cast

from animetix.models import MediaItem

WIKI_API = "https://vsbattles.fandom.com/api.php"


def _norm(s: str) -> set:
    s = (s or "").lower()
    s = re.sub(r"\(.*?\)", "", s)
    s = s.replace("uu", "u").replace("ou", "o")
    s = re.sub(r"[^a-z0-9 ]", " ", s)
    return {p for p in s.split() if len(p) > 1}


def _wiki_has_page(name: str, franchise: str) -> bool:
    """Lightweight existence check: search the wiki and name-match the results."""
    query = f"{name} {franchise} VS Battles Wiki".strip()
    params = {
        "action": "query",
        "list": "search",
        "srsearch": query,
        "srlimit": 5,
        "format": "json",
    }
    try:
        res = safe_http_request("GET", WIKI_API, params=params, timeout=12)
        res.raise_for_status()
        results = res.json().get("query", {}).get("search", [])
    except Exception:
        return False

    name_tokens = _norm(name)
    if not name_tokens:
        return False
    # The character's most distinctive token (longest) must appear in a result
    # title, and the title must share the bulk of the character's name tokens.
    distinctive = max(name_tokens, key=len)
    for r in results:
        title_tokens = _norm(r.get("title", ""))
        if distinctive in title_tokens and (
            name_tokens <= title_tokens or title_tokens <= name_tokens
        ):
            return True
    return False


class Command(BaseCommand):
    help = (
        "Tag characters with whether they have a VS Battles Wiki sheet (by popularity)."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--limit", type=int, default=1000, help="Top-N by popularity."
        )
        parser.add_argument(
            "--force", action="store_true", help="Re-check already tagged characters."
        )
        parser.add_argument(
            "--delay", type=float, default=0.35, help="Seconds between wiki calls."
        )

    def handle(self, *args, **opts):
        limit, force, delay = opts["limit"], opts["force"], opts["delay"]

        fav = Cast(
            KeyTextTransform("favourites", KeyTransform("popularity", "metadata")),
            IntegerField(),
        )
        qs = (
            MediaItem.objects.filter(media_type="Character")
            .exclude(image_url__isnull=True)
            .exclude(image_url="")
            .annotate(fav=fav)
            .order_by(F("fav").desc(nulls_last=True))[:limit]
        )
        items = list(qs)
        self.stdout.write(f"Processing {len(items)} characters (limit={limit})…")

        found = synthetic = skipped = 0
        not_found_names = []
        batch = []

        for i, m in enumerate(items, 1):
            meta = m.metadata or {}
            if (
                not force
                and isinstance(meta.get("vsbattle"), dict)
                and meta["vsbattle"].get("checked")
            ):
                skipped += 1
                continue

            franchise = meta.get("origin") or ""
            has_wiki = _wiki_has_page(m.title, franchise)
            if has_wiki:
                found += 1
            else:
                synthetic += 1
                not_found_names.append(f"{m.title} ({franchise})")

            meta["vsbattle"] = {
                "in_roster": True,
                "checked": True,
                "source": "wiki" if has_wiki else "synthetic",
            }
            m.metadata = meta
            batch.append(m)

            if len(batch) >= 100:
                MediaItem.objects.bulk_update(batch, ["metadata"])
                batch = []
                self.stdout.write(
                    f"  …{i}/{len(items)} (wiki:{found} synthetic:{synthetic})"
                )

            time.sleep(delay)

        if batch:
            MediaItem.objects.bulk_update(batch, ["metadata"])

        self.stdout.write(
            self.style.SUCCESS(
                f"Done. wiki={found} synthetic(generated at battle)={synthetic} skipped={skipped}"
            )
        )
        if not_found_names:
            self.stdout.write("Synthetic-sheet characters (no wiki page found), e.g.:")
            for n in not_found_names[:40]:
                self.stdout.write(f"  - {n}")
