from django.urls import path
from .. import api_views
from ..views.billing import billing_alert_webhook

urlpatterns = [
    path('fusions/', api_views.CreativeFusionViewSet.as_view({'get': 'list', 'post': 'create'}), name='api-fusions'),
    path('clubs/', api_views.ClubViewSet.as_view({'get': 'list', 'post': 'create'}), name='api-clubs'),
    path('clubs/<int:pk>/', api_views.ClubViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='api-club-detail'),
    path('clubs/<int:pk>/join/', api_views.ClubViewSet.as_view({'post': 'join'}), name='api-club-join'),
    path('clubs/<int:pk>/leave/', api_views.ClubViewSet.as_view({'post': 'leave'}), name='api-club-leave'),
    path('club-events/', api_views.ClubEventViewSet.as_view({'get': 'list', 'post': 'create'}), name='api-club-events'),
    path('club-events/<int:pk>/', api_views.ClubEventViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='api-club-event-detail'),
    path('achievements/', api_views.AchievementViewSet.as_view({'get': 'list'}), name='api-achievements'),
    path('search/', api_views.MediaSearchView.as_view(), name='api_search'),
    path('media/<str:media_type>/<str:item_id>/', api_views.MediaDetailView.as_view(), name='api_media_detail'),
    path('config/', api_views.ConfigView.as_view(), name='api_config'),
    path('auth/login/', api_views.LoginView.as_view(), name='api_auth_login'),
    path('auth/logout/', api_views.LogoutView.as_view(), name='api_auth_logout'),
    path('auth/register/', api_views.RegisterView.as_view(), name='api_auth_register'),
    path('auth/me/', api_views.CurrentUserView.as_view(), name='api_auth_me'),
    path('leaderboard/', api_views.LeaderboardView.as_view(), name='api_leaderboard'),
    path('profile/<str:username>/', api_views.ProfileDetailView.as_view(), name='api_profile_detail'),
    path('social/search/', api_views.UserSearchView.as_view(), name='api_user_search'),
    path('social/collection/', api_views.MyCollectionView.as_view(), name='api_collection'),
    path('social/notifications/', api_views.NotificationListView.as_view(), name='api_notifications'),
    path('social/gameplay-history/', api_views.GameplaySessionListView.as_view(), name='api_gameplay_history'),
    path('latent-space/', api_views.SampleView.as_view() if not hasattr(api_views, 'LatentSpaceDataView') else api_views.LatentSpaceDataView.as_view(), name='api_latent_space'),
    path('daily-challenge/', api_views.DailyChallengeDataView.as_view(), name='api_daily_challenge'),
    path('custom-config/', api_views.CustomConfigDataView.as_view(), name='api_custom_config'),
    path('transparency/', api_views.TransparencyDataView.as_view(), name='api_transparency'),
    path('spatial-lab/', api_views.SpatialLabDataView.as_view(), name='api_spatial_lab'),
    path('spatial-lab/generate-3d/', api_views.Generate3DDataView.as_view(), name='api_generate_3d'),
    path('spatial-lab/cinematic-reconstruction/', api_views.CinematicReconstructionView.as_view(), name='api_cinematic_reconstruction'),
    path('manga-lab/', api_views.MangaLabDataView.as_view(), name='api_manga_lab'),
    path('manga-voice/', api_views.MangaVoiceLabView.as_view(), name='manga-voice'),
    path('audio-lab/', api_views.AudioLabDataView.as_view(), name='api_audio_lab'),
    path('singularity-lab/', api_views.SingularityLabDataView.as_view(), name='api_singularity_lab'),
    path('labs/video/', api_views.VideoLabDataView.as_view(), name='api_video_lab'),
    path('labs/video/index/', api_views.VideoRAGIndexView.as_view(), name='api_video_rag_index'),
    path('labs/video/search/', api_views.VideoRAGSearchView.as_view(), name='api_video_rag_search'),
    path('labs/soundscape/', api_views.SoundscapeLabDataView.as_view(), name='api_soundscape_lab'),
    path('labs/s2s/', api_views.SpeechToSpeechLabDataView.as_view(), name='api_s2s_lab'),
    path('labs/liquid-nn/', api_views.LiquidNeuralNetworkLabView.as_view(), name='api_liquid_nn_lab'),
    path('mlops/dpo/curation/', api_views.DPOCurationView.as_view(), name='api_dpo_curation'),
    path('mlops/sota/benchmarks/', api_views.SOTABenchmarkListView.as_view(), name='api_sota_benchmarks'),
    path('mlops/dspy/optimizer/', api_views.DSPyOptimizerView.as_view(), name='api_dspy_optimizer'),
    path('graph/neighbors/', api_views.GraphNeighborsView.as_view(), name='api_graph_neighbors'),
    path('graph/debugger/', api_views.GraphDebuggerView.as_view(), name='api_graph_debugger'),
    path('graph/world-map/', api_views.GraphWorldMapView.as_view(), name='api_graph_world_map'),
    path('cognition/archetype-nexus/', api_views.ArchetypeNexusView.as_view(), name='api_archetype_nexus'),
    path('cognition/neuro-memory/', api_views.NeuroMemoryManagementView.as_view(), name='api_neuro_memory'),
    path('cognition/debate-arena/', api_views.AIDebateArenaView.as_view(), name='api_debate_arena'),
    path('companion/interact/', api_views.CompanionInteractView.as_view(), name='api_companion_interact'),
    
    # --- STREAMING IA ---
    path('stream/emoji/', api_views.EmojiStreamView.as_view(), name='api_emoji_stream'),
    path('stream/paradox/', api_views.ParadoxStreamView.as_view(), name='api_paradox_stream'),
    path('stream/agentic-rag/', api_views.AgenticRAGStreamView.as_view(), name='api_agentic_rag'),
    path('stream/animinator/', api_views.AniminatorStreamView.as_view(), name='api_animinator_stream'),
    
    # --- ARCHETYPIST (LA FORGE) ---
    path('archetypist/start/', api_views.ArchetypistStartFusionView.as_view(), name='api_archetypist_start'),
    path('archetypist/status/', api_views.ArchetypistTaskStatusView.as_view(), name='api_archetypist_status'),
    path('archetypist/theater/', api_views.TheaterListView.as_view(), name='api_theater_list'),
    path('archetypist/vn/<int:fusion_id>/', api_views.ForgeVNView.as_view(), name='api_forge_vn'),
    
    # ... autres endpoints API
    path('game/vs_battle/arena/', api_views.list_vs_battles, name='api_vs_battle_arena'),
    path('game/vs_battle/run/', api_views.run_vs_battle, name='api_vs_battle_run'),
    path('game/vs_battle/<int:battle_id>/like/', api_views.like_vs_battle, name='api_vs_battle_like'),
    path('game/classic/state/', api_views.ClassicGameStateView.as_view(), name='api_classic_state'),
    path('cognition/archetype-nexus/', api_views.ArchetypeNexusView.as_view(), name='api_archetype_nexus'),
    path('cognition/neuro-memory/', api_views.NeuroMemoryManagementView.as_view(), name='api_neuro_memory'),
    path('cognition/debate-arena/', api_views.AIDebateArenaView.as_view(), name='api_debate_arena'),
    path('cognition/counterfactual/', api_views.CounterfactualSimulatorView.as_view(), name='api_counterfactual'),
    path('game/akinetix/state/', api_views.AkinetixGameStateView.as_view(), name='api_akinetix_state'),
    path('game/akinetix/start/', api_views.AkinetixGameStartView.as_view(), name='api_akinetix_start'),
    path('game/akinetix/answer/', api_views.AkinetixGameAnswerView.as_view(), name='api_akinetix_answer'),
    path('game/akinetix/confirm/', api_views.AkinetixGameConfirmView.as_view(), name='api_akinetix_confirm'),
    path('game/akinetix-rl/state/', api_views.AkinetixRLStateView.as_view(), name='api_akinetix_rl_state'),
    path('game/akinetix-rl/start/', api_views.AkinetixRLStartView.as_view(), name='api_akinetix_rl_start'),
    path('game/akinetix-rl/answer/', api_views.AkinetixRLAnswerView.as_view(), name='api_akinetix_rl_answer'),
    path('game/animinator/ask/', api_views.AniminatorAskView.as_view(), name='api_animinator_ask'),
    path('game/emoji/state/', api_views.EmojiGameStateView.as_view(), name='api_emoji_state'),
    path('game/paradox/state/', api_views.ParadoxGameStateView.as_view(), name='api_paradox_state'),
    path('game/vision/state/', api_views.VisionGameStateView.as_view(), name='api_vision_state'),
    path('game/blindtest/state/', api_views.BlindtestGameStateView.as_view(), name='api_blindtest_state'),
    path('game/covertest/state/', api_views.CovertestGameStateView.as_view(), name='api_covertest_state'),
    path('game/world-boss/active/', api_views.ActiveWorldBossView.as_view(), name='api_world_boss_active'),
    path('game/world-boss/attack/', api_views.WorldBossAttackView.as_view(), name='api_world_boss_attack'),
    path('game/duel/create/', api_views.CreateDuelRoomView.as_view(), name='api_duel_create'),
    path('game/duel/join/', api_views.JoinDuelRoomView.as_view(), name='api_duel_join'),
    path('game/duel/matchmaking/', api_views.MatchmakingView.as_view(), name='api_duel_matchmaking'),
    path('explore/', api_views.MediaExploreView.as_view(), name='api_explore'),
    path('billing/webhook/', billing_alert_webhook, name='api_billing_webhook'),
]

