from django.urls import path

from .. import api_views
from ..api import billing, monitoring, observability
from ..views.billing import billing_alert_webhook

urlpatterns = [
    # --- ECONOMY & BILLING ---
    path(
        "billing/wallet/mine/", billing.WalletMineView.as_view(), name="api_wallet_mine"
    ),
    path(
        "billing/wallet/watch-ad/",
        billing.WalletWatchAdView.as_view(),
        name="api_wallet_watch_ad",
    ),
    path(
        "billing/wallet/balance/",
        billing.WalletBalanceView.as_view(),
        name="api_wallet_balance",
    ),
    path(
        "fusions/",
        api_views.CreativeFusionViewSet.as_view({"get": "list", "post": "create"}),
        name="api-fusions",
    ),
    path(
        "clubs/",
        api_views.ClubViewSet.as_view({"get": "list", "post": "create"}),
        name="api-clubs",
    ),
    path(
        "clubs/<int:pk>/",
        api_views.ClubViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="api-club-detail",
    ),
    path(
        "clubs/<int:pk>/join/",
        api_views.ClubViewSet.as_view({"post": "join"}),
        name="api-club-join",
    ),
    path(
        "clubs/<int:pk>/leave/",
        api_views.ClubViewSet.as_view({"post": "leave"}),
        name="api-club-leave",
    ),
    path(
        "club-events/",
        api_views.ClubEventViewSet.as_view({"get": "list", "post": "create"}),
        name="api-club-events",
    ),
    path(
        "club-events/<int:pk>/",
        api_views.ClubEventViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="api-club-event-detail",
    ),
    path(
        "achievements/",
        api_views.AchievementViewSet.as_view({"get": "list"}),
        name="api-achievements",
    ),
    path("search/", api_views.MediaSearchView.as_view(), name="api_search"),
    # Same view, new path: the per-target visual search (`target=work|character`)
    # this endpoint now serves (see task-5-brief.md). Additive -- `search/`
    # keeps working for the existing text/legacy-image callers until the
    # frontend migrates (a later task) to this one.
    path(
        "media/search/",
        api_views.MediaSearchView.as_view(),
        name="api_media_search",
    ),
    path(
        "media/Manga/suwayomi-image/",
        api_views.suwayomi_image_proxy,
        name="api_suwayomi_image_proxy",
    ),
    path(
        "media/<str:media_type>/<str:item_id>/",
        api_views.MediaDetailView.as_view(),
        name="api_media_detail",
    ),
    path(
        "media/favorites/",
        api_views.FavoriteMangaListView.as_view(),
        name="api_favorite_manga_list",
    ),
    path(
        "media/Manga/<str:media_id>/favorite/",
        api_views.FavoriteMangaToggleView.as_view(),
        name="api_manga_favorite_toggle",
    ),
    path(
        "media/Manga/<str:media_id>/chapters/",
        api_views.MangaChapterListView.as_view(),
        name="api_manga_chapters",
    ),
    path(
        "media/Manga/<str:media_id>/chapters/<str:chapter_number>/",
        api_views.MangaChapterDetailView.as_view(),
        name="api_manga_chapter_detail",
    ),
    path(
        "media/Manga/<str:media_id>/chapters/<str:chapter_number>/sync/",
        api_views.MangaChapterSyncView.as_view(),
        name="api_manga_chapter_sync",
    ),
    path(
        "profile/trackers/",
        api_views.TrackerConnectionListView.as_view(),
        name="api_tracker_connections",
    ),
    path(
        "profile/trackers/link/",
        api_views.TrackerConnectionLinkView.as_view(),
        name="api_tracker_link",
    ),
    path(
        "profile/trackers/unlink/",
        api_views.TrackerConnectionUnlinkView.as_view(),
        name="api_tracker_unlink",
    ),
    path(
        "explore/suwayomi/sources/",
        api_views.SuwayomiSourcesView.as_view(),
        name="api_suwayomi_sources",
    ),
    path(
        "explore/suwayomi/search/",
        api_views.SuwayomiSearchView.as_view(),
        name="api_suwayomi_search",
    ),
    path(
        "explore/suwayomi/import/",
        api_views.SuwayomiImportView.as_view(),
        name="api_suwayomi_import",
    ),
    path(
        "explore/suwayomi/extensions/",
        api_views.SuwayomiExtensionsListView.as_view(),
        name="api_suwayomi_extensions",
    ),
    path(
        "explore/suwayomi/extensions/action/",
        api_views.SuwayomiExtensionsActionView.as_view(),
        name="api_suwayomi_extensions_action",
    ),
    path("config/", api_views.ConfigView.as_view(), name="api_config"),
    path("auth/login/", api_views.LoginView.as_view(), name="api_auth_login"),
    path("auth/logout/", api_views.LogoutView.as_view(), name="api_auth_logout"),
    path("auth/register/", api_views.RegisterView.as_view(), name="api_auth_register"),
    path("auth/me/", api_views.CurrentUserView.as_view(), name="api_auth_me"),
    path("leaderboard/", api_views.LeaderboardView.as_view(), name="api_leaderboard"),
    path(
        "profile/<str:username>/",
        api_views.ProfileDetailView.as_view(),
        name="api_profile_detail",
    ),
    path("social/search/", api_views.UserSearchView.as_view(), name="api_user_search"),
    path(
        "social/collection/",
        api_views.MyCollectionView.as_view(),
        name="api_collection",
    ),
    path(
        "social/notifications/",
        api_views.NotificationListView.as_view(),
        name="api_notifications",
    ),
    path(
        "social/gameplay-history/",
        api_views.GameplaySessionListView.as_view(),
        name="api_gameplay_history",
    ),
    path(
        "social/dashboard/",
        api_views.SocialViewSet.as_view({"get": "dashboard"}),
        name="api_social_dashboard",
    ),
    path(
        "social/toggle_follow/<int:pk>/",
        api_views.SocialViewSet.as_view({"post": "toggle_follow"}),
        name="api_social_toggle_follow",
    ),
    path(
        "sync/offline/",
        api_views.sync_offline_data,
        name="sync_offline_data",
    ),
    path(
        "latent-space/",
        api_views.LatentSpaceDataView.as_view(),
        name="api_latent_space",
    ),
    path(
        "daily-challenge/",
        api_views.DailyChallengeDataView.as_view(),
        name="api_daily_challenge",
    ),
    path(
        "custom-config/",
        api_views.CustomConfigDataView.as_view(),
        name="api_custom_config",
    ),
    path(
        "transparency/",
        api_views.TransparencyDataView.as_view(),
        name="api_transparency",
    ),
    path(
        "labs/spatial/", api_views.SpatialLabDataView.as_view(), name="api_spatial_lab"
    ),
    path(
        "labs/spatial/generate-3d/",
        api_views.Generate3DDataView.as_view(),
        name="api_generate_3d",
    ),
    path(
        "labs/spatial/cinematic/",
        api_views.CinematicReconstructionView.as_view(),
        name="api_cinematic_reconstruction",
    ),
    path("labs/manga-lab/", api_views.MangaLabDataView.as_view(), name="api_manga_lab"),
    path(
        "labs/manga-lab/clean/",
        api_views.MangaCleanLabView.as_view(),
        name="api_manga_clean_lab",
    ),
    path(
        "labs/manga-lab/translate/",
        api_views.MangaTranslateLabView.as_view(),
        name="api_manga_translate_lab",
    ),
    path(
        "labs/manga-voice/", api_views.MangaVoiceLabView.as_view(), name="manga-voice"
    ),
    path("labs/audio/", api_views.AudioLabDataView.as_view(), name="api_audio_lab"),
    path(
        "labs/audio/soundscape/",
        api_views.SoundscapeGenerationView.as_view(),
        name="api_audio_soundscape",
    ),
    path(
        "labs/audio/s2s/",
        api_views.SpeechToSpeechLabView.as_view(),
        name="api_audio_s2s",
    ),
    path(
        "labs/audio/seiyuu/",
        api_views.SeiyuuDiscoveryView.as_view(),
        name="api_audio_seiyuu",
    ),
    path(
        "labs/audio/seiyuu/ingest/",
        api_views.VoiceProfileIngestView.as_view(),
        name="api_audio_seiyuu_ingest",
    ),
    path(
        "singularity-lab/",
        api_views.SingularityLabDataView.as_view(),
        name="api_singularity_lab",
    ),
    path(
        "singularity-lab/command-center/",
        api_views.SingularityCommandCenterView.as_view(),
        name="api_singularity_command_center",
    ),
    path("labs/video/", api_views.VideoLabDataView.as_view(), name="api_video_lab"),
    path(
        "labs/video/fatezero/",
        api_views.VideoFateZeroLabView.as_view(),
        name="api_video_fatezero_lab",
    ),
    path(
        "labs/video/index/",
        api_views.VideoRAGIndexView.as_view(),
        name="api_video_rag_index",
    ),
    path(
        "labs/video/search/",
        api_views.VideoRAGSearchView.as_view(),
        name="api_video_rag_search",
    ),
    path(
        "labs/soundscape/",
        api_views.SoundscapeGenerationView.as_view(),
        name="api_soundscape_lab",
    ),
    path("labs/s2s/", api_views.SpeechToSpeechLabView.as_view(), name="api_s2s_lab"),
    path(
        "labs/liquid-nn/",
        api_views.LiquidNeuralNetworkLabView.as_view(),
        name="api_liquid_nn_lab",
    ),
    path("labs/tot/", api_views.TreeOfThoughtsLabView.as_view(), name="api_tot_lab"),
    path(
        "labs/voice-cloning/",
        api_views.VoiceCloningLabView.as_view(),
        name="api_voice_cloning",
    ),
    path(
        "labs/diagnostics/",
        api_views.NeuralDiagnosticsLabView.as_view(),
        name="api_neural_diagnostics",
    ),
    path(
        "mlops/dpo/curation/",
        api_views.DPOCurationViewSet.as_view({"get": "list", "post": "create"}),
        name="api_dpo_curation",
    ),
    path(
        "mlops/dpo/feedback-loop/",
        api_views.DPOFeedbackLoopView.as_view(),
        name="api_dpo_feedback_loop",
    ),
    path(
        "mlops/sota/benchmarks/",
        api_views.SOTABenchmarkListView.as_view(),
        name="api_sota_benchmarks",
    ),
    path(
        "mlops/dspy/optimizer/",
        api_views.DSPyOptimizerView.as_view(),
        name="api_dspy_optimizer",
    ),
    path(
        "mlops/safety/events/",
        api_views.AISafetyEventViewSet.as_view({"get": "list"}),
        name="api_safety_events",
    ),
    path(
        "mlops/adapters/", api_views.AdaptersView.as_view(), name="api_mlops_adapters"
    ),
    path(
        "mlops/feedback/submit/",
        api_views.AIFeedbackAPIView.as_view(),
        name="submit_ai_feedback",
    ),
    path(
        "mlops/eval/failures/",
        api_views.AIREvaluationViewSet.as_view({"get": "failures"}),
        name="mlops_eval_failures",
    ),
    path(
        "mlops/open-data/",
        api_views.OpenDatasetListView.as_view(),
        name="open_dataset_list",
    ),
    path(
        "mlops/open-data/download/<str:dataset_id>/",
        api_views.OpenDatasetDownloadView.as_view(),
        name="open_dataset_download",
    ),
    path(
        "mlops/gold-dataset/",
        api_views.GoldDatasetViewSet.as_view({"get": "list", "post": "create"}),
        name="mlops_gold_dataset_list",
    ),
    path(
        "mlops/gold-dataset/<int:pk>/validate/",
        api_views.GoldDatasetViewSet.as_view({"post": "validate"}),
        name="mlops_gold_dataset_validate",
    ),
    path(
        "mlops/gold-dataset/sync_positive_feedback/",
        api_views.GoldDatasetViewSet.as_view({"post": "sync_positive_feedback"}),
        name="mlops_gold_dataset_sync",
    ),
    path(
        "mlops/gold-dataset/<int:pk>/",
        api_views.GoldDatasetViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="mlops_gold_dataset_detail",
    ),
    path(
        "admin/ai_eval/data/",
        api_views.AIREvaluationViewSet.as_view({"get": "stats"}),
        name="admin_ai_eval_data",
    ),
    path(
        "graph/neighbors/",
        api_views.GraphNeighborsView.as_view(),
        name="api_graph_neighbors",
    ),
    path(
        "graph/debugger/",
        api_views.GraphDebuggerView.as_view(),
        name="api_graph_debugger",
    ),
    path(
        "graph/world-map/",
        api_views.GraphWorldMapView.as_view(),
        name="api_graph_world_map",
    ),
    # path('cognition/archetype-nexus/', api_views.ArchetypeNexusView.as_view(), name='api_archetype_nexus'),
    # path('cognition/neuro-memory/', api_views.NeuroMemoryManagementView.as_view(), name='api_neuro_memory'),
    # path('cognition/debate-arena/', api_views.AIDebateArenaView.as_view(), name='api_debate_arena'),
    path(
        "companion/interact/",
        api_views.CompanionInteractView.as_view(),
        name="api_companion_interact",
    ),
    # --- STREAMING IA ---
    path("stream/emoji/", api_views.EmojiStreamView.as_view(), name="api_emoji_stream"),
    path(
        "stream/paradox/",
        api_views.ParadoxStreamView.as_view(),
        name="api_paradox_stream",
    ),
    path(
        "stream/agentic-rag/",
        api_views.AgenticRAGStreamView.as_view(),
        name="api_agentic_rag",
    ),
    path(
        "stream/animinator/",
        api_views.AniminatorStreamView.as_view(),
        name="api_animinator_stream",
    ),
    path(
        "stream/tot/",
        api_views.ToTStreamView.as_view(),
        name="api_tot_stream",
    ),
    # --- ARCHETYPIST (LA FORGE) ---
    path(
        "archetypist/start/",
        api_views.ArchetypistStartFusionView.as_view(),
        name="api_archetypist_start",
    ),
    path(
        "archetypist/status/",
        api_views.ArchetypistTaskStatusView.as_view(),
        name="api_archetypist_status",
    ),
    path(
        "archetypist/theater/",
        api_views.TheaterListView.as_view(),
        name="api_theater_list",
    ),
    path(
        "archetypist/vn/<int:fusion_id>/",
        api_views.ForgeVNView.as_view(),
        name="api_forge_vn",
    ),
    # ... autres endpoints API
    path(
        "game/vs_battle/arena/", api_views.list_vs_battles, name="api_vs_battle_arena"
    ),
    path(
        "game/vs_battle/characters/",
        api_views.list_vs_characters,
        name="api_vs_battle_characters",
    ),
    path("game/vs_battle/run/", api_views.run_vs_battle, name="api_vs_battle_run"),
    path(
        "game/vs_battle/<int:battle_id>/like/",
        api_views.like_vs_battle,
        name="api_vs_battle_like",
    ),
    path(
        "game/classic/titles/",
        api_views.ClassicGameTitlesView.as_view(),
        name="api_classic_titles",
    ),
    path(
        "game/classic/state/",
        api_views.ClassicGameStateView.as_view(),
        name="api_classic_state",
    ),
    path(
        "game/classic/start/",
        api_views.ClassicGameStartView.as_view(),
        name="api_classic_start",
    ),
    path(
        "game/classic/guess/",
        api_views.ClassicGameGuessView.as_view(),
        name="api_classic_guess",
    ),
    path(
        "game/classic/reveal/",
        api_views.ClassicGameRevealView.as_view(),
        name="api_classic_reveal",
    ),
    path(
        "cognition/archetype-nexus/",
        api_views.ArchetypeNexusView.as_view(),
        name="api_archetype_nexus",
    ),
    path(
        "cognition/neuro-memory/",
        api_views.NeuroMemoryManagementView.as_view(),
        name="api_neuro_memory",
    ),
    path(
        "cognition/debate-arena/",
        api_views.AIDebateArenaView.as_view(),
        name="api_debate_arena",
    ),
    path(
        "cognition/cove-oracle/",
        api_views.CoveOracleView.as_view(),
        name="api_cove_oracle",
    ),
    path(
        "cognition/cfr-strategy-lab/",
        api_views.CFRStrategyLabView.as_view(),
        name="api_cfr_strategy_lab",
    ),
    path(
        "cognition/counterfactual/",
        api_views.CounterfactualSimulatorView.as_view(),
        name="api_counterfactual",
    ),
    path(
        "game/akinetix/state/",
        api_views.AkinetixGameStateView.as_view(),
        name="api_akinetix_state",
    ),
    path(
        "game/akinetix/start/",
        api_views.AkinetixGameStartView.as_view(),
        name="api_akinetix_start",
    ),
    path(
        "game/akinetix/answer/",
        api_views.AkinetixGameAnswerView.as_view(),
        name="api_akinetix_answer",
    ),
    path(
        "game/akinetix/confirm/",
        api_views.AkinetixGameConfirmView.as_view(),
        name="api_akinetix_confirm",
    ),
    path(
        "game/quiz-who/start/",
        api_views.QuiEstCeStartView.as_view(),
        name="api_quiz_who_start",
    ),
    path(
        "game/quiz-who/ask/",
        api_views.QuiEstCeAskView.as_view(),
        name="api_quiz_who_ask",
    ),
    path(
        "game/quiz-who/guess/",
        api_views.QuiEstCeGuessView.as_view(),
        name="api_quiz_who_guess",
    ),
    path(
        "game/akinetix-rl/state/",
        api_views.AkinetixRLStateView.as_view(),
        name="api_akinetix_rl_state",
    ),
    path(
        "game/akinetix-rl/start/",
        api_views.AkinetixRLStartView.as_view(),
        name="api_akinetix_rl_start",
    ),
    path(
        "game/akinetix-rl/answer/",
        api_views.AkinetixRLAnswerView.as_view(),
        name="api_akinetix_rl_answer",
    ),
    path(
        "game/animinator/ask/",
        api_views.AniminatorAskView.as_view(),
        name="api_animinator_ask",
    ),
    path(
        "game/animinator/guess/",
        api_views.AniminatorGuessView.as_view(),
        name="api_animinator_guess",
    ),
    path(
        "game/emoji/state/",
        api_views.EmojiGameStateView.as_view(),
        name="api_emoji_state",
    ),
    path(
        "game/emoji/start/",
        api_views.EmojiGameStartView.as_view(),
        name="api_emoji_start",
    ),
    path(
        "game/emoji/guess/",
        api_views.EmojiGameGuessView.as_view(),
        name="api_emoji_guess",
    ),
    path(
        "game/emoji/suggest/",
        api_views.EmojiGameSuggestView.as_view(),
        name="api_emoji_suggest",
    ),
    path(
        "game/emoji/giveup/",
        api_views.EmojiGameGiveUpView.as_view(),
        name="api_emoji_giveup",
    ),
    path(
        "game/paradox/state/",
        api_views.ParadoxGameStateView.as_view(),
        name="api_paradox_state",
    ),
    path(
        "game/paradox/start/",
        api_views.ParadoxGameStartView.as_view(),
        name="api_paradox_start",
    ),
    path(
        "game/paradox/move/",
        api_views.ParadoxGameGuessView.as_view(),
        name="api_paradox_guess",
    ),
    path(
        "game/vision/state/",
        api_views.VisionGameStateView.as_view(),
        name="api_vision_state",
    ),
    path(
        "game/vision/start/",
        api_views.VisionGameStartView.as_view(),
        name="api_vision_start",
    ),
    path(
        "game/vision/guess/",
        api_views.VisionGameGuessView.as_view(),
        name="api_vision_guess",
    ),
    path(
        "game/blindtest/state/",
        api_views.BlindtestGameStateView.as_view(),
        name="api_blindtest_state",
    ),
    path(
        "game/blindtest/start/",
        api_views.BlindtestGameStartView.as_view(),
        name="api_blindtest_start",
    ),
    path(
        "game/blindtest/guess/",
        api_views.BlindtestGameGuessView.as_view(),
        name="api_blindtest_guess",
    ),
    path(
        "game/blindtest/titles/",
        api_views.BlindtestTitlesView.as_view(),
        name="api_blindtest_titles",
    ),
    path(
        "game/covertest/titles/",
        api_views.CovertestTitlesView.as_view(),
        name="api_covertest_titles",
    ),
    path(
        "game/covertest/state/",
        api_views.CovertestGameStateView.as_view(),
        name="api_covertest_state",
    ),
    path(
        "game/covertest/reveal/",
        api_views.CovertestGameRevealView.as_view(),
        name="api_covertest_reveal",
    ),
    path(
        "game/covertest/start/",
        api_views.CovertestGameStartView.as_view(),
        name="api_covertest_start",
    ),
    path(
        "game/covertest/guess/",
        api_views.CovertestGameGuessView.as_view(),
        name="api_covertest_guess",
    ),
    path(
        "game/world-boss/active/",
        api_views.ActiveWorldBossView.as_view(),
        name="api_world_boss_active",
    ),
    path(
        "game/world-boss/question/",
        api_views.WorldBossQuestionView.as_view(),
        name="api_world_boss_question",
    ),
    path(
        "game/world-boss/answer/",
        api_views.WorldBossAnswerView.as_view(),
        name="api_world_boss_answer",
    ),
    path(
        "game/world-boss/leaderboard/",
        api_views.WorldBossLeaderboardView.as_view(),
        name="api_world_boss_leaderboard",
    ),
    path(
        "game/duel/create/",
        api_views.CreateDuelRoomView.as_view(),
        name="api_duel_create",
    ),
    path("game/duel/join/", api_views.JoinDuelRoomView.as_view(), name="api_duel_join"),
    path(
        "game/duel/matchmaking/",
        api_views.MatchmakingView.as_view(),
        name="api_duel_matchmaking",
    ),
    path(
        "game/undercover/public-rooms/",
        api_views.UndercoverPublicRoomsView.as_view(),
        name="api_undercover_public_rooms",
    ),
    path("explore/", api_views.MediaExploreView.as_view(), name="api_explore"),
    path(
        "explore/seichijunrei/",
        api_views.SeichijunreiMapView.as_view(),
        name="api_seichijunrei",
    ),
    path("market/wiki/", api_views.MarketWikiView.as_view(), name="api_market_wiki"),
    path(
        "multiverse/gallery/",
        api_views.MultiverseGalleryView.as_view(),
        name="api_multiverse_gallery",
    ),
    path(
        "multiverse/catalog/",
        api_views.MultiverseCatalogView.as_view(),
        name="api_multiverse_catalog",
    ),
    path(
        "multiverse/<str:universe_name>/export-pdf/",
        api_views.MultiverseExportPDFView.as_view(),
        name="api_multiverse_export_pdf",
    ),
    path("billing/webhook/", billing_alert_webhook, name="api_billing_webhook"),
    path(
        "billing/log_ad_event/",
        api_views.AdEventLoggingAPIView.as_view(),
        name="api_log_ad_event",
    ),
    path(
        "admin/ttc-monitoring/",
        api_views.TTCMonitoringAPIView.as_view(),
        name="api_ttc_monitoring",
    ),
    path(
        "admin/financials/",
        api_views.AdminFinancialsAPIView.as_view(),
        name="api_admin_financials",
    ),
    path(
        "admin/economics/",
        api_views.AdminEconomicAuditAPIView.as_view(),
        name="api_admin_economics",
    ),
    path(
        "curation/",
        api_views.DataCurationTicketViewSet.as_view({"get": "list"}),
        name="api_curation_tickets",
    ),
    path(
        "curation/<int:pk>/resolve/",
        api_views.DataCurationTicketViewSet.as_view({"post": "resolve"}),
        name="api_resolve_ticket",
    ),
    path(
        "curation/stats/",
        api_views.DataCurationTicketViewSet.as_view({"get": "stats"}),
        name="api_curation_stats",
    ),
    path(
        "admin/pipelines/control/<str:action>/",
        monitoring.PipelineControlView.as_view(),
        name="api_pipeline_control",
    ),
    path(
        "admin/observability/",
        observability.ObservabilityView.as_view(),
        name="api_observability",
    ),
    path(
        "admin/users/",
        api_views.UserManagementViewSet.as_view({"get": "list"}),
        name="api_admin_users",
    ),
    path(
        "admin/users/<int:pk>/toggle-staff/",
        api_views.UserManagementViewSet.as_view({"post": "toggle_staff"}),
        name="api_admin_toggle_staff",
    ),
    path(
        "admin/users/<int:pk>/toggle-active/",
        api_views.UserManagementViewSet.as_view({"post": "toggle_active"}),
        name="api_admin_toggle_active",
    ),
    # --- B2B DEVELOPER API (Pro tier, free/manual) ---
    path("developer/rag/", api_views.DeveloperRAGView.as_view(), name="developer_rag"),
    path(
        "developer/subscribe/",
        api_views.DeveloperSubscriptionMockView.as_view(),
        name="developer_subscribe_mock",
    ),
    path(
        "developer/api-key/",
        api_views.DeveloperApiKeyView.as_view(),
        name="developer_api_key",
    ),
]
