from .classic import *
from .akinetix import *
from .emoji import *
from .paradox import *
from .vision import *
from .blindtest import *
from .covertest import *
from .akinetix_rl import *
from .archetypist import *
from .vs_battle import *
