import React from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useUIStore } from './store/uiStore';
import { useAuthStore } from './store/authStore';
import { DynamicAuraWrapper } from './components/shared/DynamicAuraWrapper';
import { AnimatedPage } from './components/ui/AnimatedPage';
import { Menu, Zap, ArrowRight } from 'lucide-react';
import './App.css';

const App: React.FC = () => {
  const { t, i18n } = useTranslation();
  const toggleSidebar = useUIStore((state) => state.toggleSidebar);
  const { user, isAuthenticated } = useAuthStore();

  const isEn = i18n.language.startsWith('en');

  // Solo Challenges list matching the premium character card layout
  const modesSolo = [
    {
      titre: 'Akinetix',
      titre_brush_1: 'AKINETIX',
      titre_brush_2: isEn ? 'THE SEER' : 'LE DEVIN',
      description: isEn 
        ? 'The artificial intelligence guesses your favorite anime or manga character.' 
        : "L'intelligence artificielle devine votre personnage d'anime ou de manga.",
      icon_url: '/static/img/modes/akinetix.png',
      gradient: 'from-amber-400 to-orange-600 dark:from-amber-500/80 dark:to-orange-700/80',
      url: '/akinetix/',
    },
    {
      titre: 'Classic',
      titre_brush_1: isEn ? 'CLASSIC' : 'CLASSIQUE',
      titre_brush_2: isEn ? 'THE QUIZ' : 'LE QUIZ',
      description: isEn 
        ? 'Guess the anime from clues, screenshots, or audio clips.' 
        : "Devinez l'anime à partir d'indices, d'images ou d'extraits sonores.",
      icon_url: '/static/img/modes/classic.png',
      gradient: 'from-blue-400 to-indigo-600 dark:from-blue-500/80 dark:to-indigo-700/80',
      url: '/game/classic/',
    },
    {
      titre: 'Paradox',
      titre_brush_1: 'PARADOX',
      titre_brush_2: isEn ? 'THE ODD ONE' : "L'INTRUS",
      description: isEn 
        ? 'Identify the odd one out or temporal paradox generated by the AI.' 
        : "Identifiez l'intrus ou le paradoxe temporel parmi les propositions de l'IA.",
      icon_url: '/static/img/modes/paradox.png',
      gradient: 'from-purple-400 to-pink-600 dark:from-purple-500/80 dark:to-pink-700/80',
      url: '/paradox/',
    },
    {
      titre: 'Emoji',
      titre_brush_1: 'EMOJI QUEST',
      titre_brush_2: isEn ? 'DECODING' : 'DÉCRYPTAGE',
      description: isEn 
        ? 'Decode anime and manga titles hidden behind combinations of emojis.' 
        : "Décodez les titres d'anime et de manga cachés derrière des combinaisons d'emojis.",
      icon_url: '/static/img/modes/emoji.png',
      gradient: 'from-emerald-400 to-teal-600 dark:from-emerald-500/80 dark:to-teal-700/80',
      url: '/emoji/',
    },
    {
      titre: 'Covertest',
      titre_brush_1: 'COVER QUEST',
      titre_brush_2: isEn ? 'THE PUZZLE' : 'LE CASSE-TÊTE',
      description: isEn 
        ? 'Rebuild blurry or scrambled manga covers generated by the AI.' 
        : "Reconnaissez les couvertures de mangas floutées ou mélangées par l'IA.",
      icon_url: '/static/img/modes/visionquest.png',
      gradient: 'from-rose-400 to-red-600 dark:from-rose-500/80 dark:to-red-700/80',
      url: '/covertest/',
    },
    {
      titre: 'Animinator',
      titre_brush_1: 'ANIMINATOR',
      titre_brush_2: isEn ? 'SYNTHESIS' : 'LA SYNTHÈSE',
      description: isEn 
        ? 'The AI generates a customized character. Guess who it is!' 
        : "L'IA génère un personnage personnalisé à partir d'indices. Devinez qui c'est !",
      icon_url: '/static/img/modes/animinator.png',
      gradient: 'from-cyan-400 to-blue-600 dark:from-cyan-500/80 dark:to-blue-700/80',
      url: '/animinator/',
    },
    {
      titre: 'Blindtest',
      titre_brush_1: 'ANIME',
      titre_brush_2: 'BLINDTEST',
      description: isEn 
        ? 'Recognize legendary OSTs transformed or filtered by AI.' 
        : "Reconnaissez les OST mythiques transformées ou filtrées par l'IA.",
      icon_url: '/static/img/modes/blindTest.png',
      gradient: 'from-emerald-400 to-green-600 dark:from-emerald-500/80 dark:to-green-700/80',
      url: '/blindtest/',
    },
    {
      titre: 'VsBattle',
      titre_brush_1: 'ARENA',
      titre_brush_2: 'ULTIMATUM',
      description: isEn 
        ? 'Trans-dimensional duels moderated by AI.' 
        : "Duels trans-dimensionnels arbitrés par l'IA.",
      icon_url: '/static/img/modes/VSBattle.png',
      gradient: 'from-red-500 to-red-900 dark:from-red-600/80 dark:to-red-950/80',
      url: '/game/vsbattle/',
    },
  ];

  // Multiplayer modes list
  const modesMulti = [
    {
      titre: 'Undercover',
      description: isEn 
        ? 'Unmask the intruder among your friends in a secret word match.' 
        : 'Démasquez l\'intrus parmi vos amis dans une partie de mots infiltrés.',
      icon_url: '/static/img/modes/undercover.png',
      url: '/game/duel/lobby/',
    },
    {
      titre: 'Code Manga',
      description: isEn 
        ? 'Make your team guess anime/manga cards with the minimum amount of words.' 
        : 'Faites deviner des cartes d\'anime/manga avec le moins d\'indices possibles.',
      icon_url: '/static/img/modes/codemanga.png',
      url: '/game/duel/lobby/',
    },
  ];

  // Creative modes list
  const modesCreative = [
    {
      titre: isEn ? 'CREATIVE FORGE' : 'FORGE CRÉATIVE',
      titre_sub: isEn ? 'ACCESS THE AI MEDIA LABORATORIES' : 'ACCÉDEZ AUX LABORATOIRES DE MÉDIAS IA',
      fusion_image: '/static/img/modes/fusion.png',
      url: '/forge-hub/',
    },
  ];

  return (
    <div className="w-full bg-transparent transition-colors duration-500 bg-manga-overlay">
        
        {/* HERO & NAV UNIFIED CONTAINER */}
        <div className="hero-bg w-full transition-all duration-500 shadow-sm border-b border-gray-100/10 dark:border-navy-950/10">
          
          {/* INTEGRATED TOP NAV */}
          <div className="max-w-[1600px] mx-auto px-6 md:px-12 py-8 flex items-center justify-between">
            <div className="flex items-center gap-6">
              <button 
                className="bg-black text-white p-3 rounded-2xl hover:scale-110 active:scale-95 transition shadow-lg" 
                onClick={() => toggleSidebar()}
              >
                <Menu className="w-6 h-6" />
              </button>
              <Link to="/" className="flex items-center no-underline">
                <img src="/static/img/logo/white_logo.png" alt="Logo" className="h-8 dark:hidden" />
                <img src="/static/img/logo/logo.png" alt="Logo" className="h-8 hidden dark:block" />
              </Link>
            </div>
            
            <div className="hidden lg:flex items-center gap-8">
              <Link 
                to="/daily-challenge/" 
                className="bg-yellow-400 hover:bg-yellow-500 text-black font-black italic manga-font text-[10px] py-2.5 px-6 rounded-xl shadow-lg hover:scale-105 transition-all no-underline"
              >
                {t('nav.daily', 'Défi Quotidien')}
              </Link>
              <Link 
                to="/leaderboard/" 
                className="manga-font text-xs hover:text-yellow-400 transition-colors no-underline text-black dark:text-white uppercase font-black italic"
              >
                {t('nav.leaderboard', 'Classement')}
              </Link>
              <Link 
                to="/latent-space/" 
                className="manga-font text-xs hover:text-yellow-400 transition-colors no-underline text-black dark:text-white uppercase font-black italic"
              >
                {t('navbar.latent', 'Latent Space')}
              </Link>
            </div>

            <div className="flex items-center gap-4 pointer-events-auto">
              {isAuthenticated && user && (
                <div className="hidden sm:flex flex-col items-end">
                  <span className="text-[10px] font-bold uppercase text-yellow-600 dark:text-yellow-400 tracking-widest">
                    {user.tier === 'premium' ? 'Premium' : 'Explorateur'}
                  </span>
                  <span className="text-xs font-black italic manga-font text-black dark:text-white">{user.username}</span>
                </div>
              )}
            </div>
          </div>

          {/* SECTION HERO CONTENT */}
          <section className="max-w-[1600px] mx-auto px-6 md:px-20 py-20 md:pb-32 min-h-[500px] flex flex-col md:flex-row items-center justify-between gap-12">
            <div className="z-10 md:w-1/2 text-left">
              <h1 className="text-6xl md:text-8xl font-black italic tracking-tighter mb-8 uppercase text-black dark:text-white manga-font leading-none">
                ANIMETIX
              </h1>
              <p className="text-xl md:text-2xl mb-10 text-gray-700 dark:text-gray-300 font-medium leading-relaxed max-w-lg">
                {isEn ? 'Artificial intelligence in service of your passion.' : "L'intelligence artificielle au service de votre passion."}
              </p>
              <div className="flex flex-wrap gap-6">
                <Link 
                  to="/daily-challenge/" 
                  className="bg-yellow-400 hover:bg-yellow-500 text-black font-black italic manga-font text-sm py-4 px-10 rounded-2xl shadow-2xl hover:scale-105 active:scale-95 transition-all no-underline inline-block border-2 border-black"
                >
                  {t('nav.daily', 'Défi Quotidien')}
                </Link>
                <Link 
                  to="/leaderboard/" 
                  className="bg-gray-800 dark:bg-gray-700 text-white font-black italic manga-font py-4 px-10 rounded-2xl text-sm tracking-wider uppercase transition-all duration-300 hover:bg-black dark:hover:bg-gray-600 hover:scale-105 active:scale-95 no-underline inline-block shadow-2xl"
                >
                  {t('nav.leaderboard', 'Classement')}
                </Link>
              </div>
            </div>
            
            <div className="md:w-1/2 relative mt-10 md:mt-0 flex justify-center">
              <DynamicAuraWrapper>
                <img 
                  src="/static/img/hero.png" 
                  alt="Hero Image" 
                  className="w-[500px] md:w-[600px] z-10 relative hero-img transform"
                />
              </DynamicAuraWrapper>
            </div>
          </section>
        </div>

        {/* CONTENT WRAPPER MATCHING HERO BACKGROUND */}
        <div className="max-w-[1600px] mx-auto px-6 md:px-10 pb-20 mt-12 bg-transparent rounded-[3rem] transition-colors duration-500">
          
          {/* SECTION MODES SOLO (CHARACTER CARDS STYLE) */}
          <section className="py-16 text-left">
            <h2 className="text-3xl font-black mb-12 flex items-baseline text-black dark:text-white uppercase italic manga-font">
              {isEn ? 'Solo Challenges' : 'Défis Solo'}
              <span className="text-yellow-400 text-4xl leading-none ml-1">.</span>
            </h2>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-y-16 gap-x-12">
              {modesSolo.map((mode, index) => (
                <div 
                  key={mode.titre}
                  className="relative w-full h-[200px] char-card-group cursor-pointer animate-float"
                  style={{ animationDelay: `0.${index}s` }}
                >
                  <Link to={mode.url} className="block h-full relative no-underline">
                    
                    {/* 1. BACKGROUND LAYER */}
                    <div className="absolute inset-0 rounded-[24px] overflow-hidden shadow-lg char-card-bg">
                      <div className={`absolute inset-0 bg-gradient-to-br ${mode.gradient}`}></div>
                      <img 
                        src="https://www.transparenttextures.com/patterns/stardust.png" 
                        className="absolute inset-0 w-full h-full object-cover opacity-40 mix-blend-screen" 
                        alt="Stars"
                      />
                    </div>

                    {/* 2. TEXT LAYER */}
                    <div className="absolute top-[5%] -left-4 z-30 transition-transform duration-500 char-card-text pointer-events-none">
                      <h2 
                        className="manga-font text-white text-4xl leading-[0.7] -rotate-12 tracking-tighter uppercase whitespace-nowrap" 
                        style={{ textShadow: '-1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000, 0 4px 10px rgba(0,0,0,0.5)' }}
                      >
                        {mode.titre_brush_1}<br />
                        <span className="text-yellow-400 text-2xl ml-6 tracking-normal">{mode.titre_brush_2}</span>
                      </h2>
                      <p 
                        className="manga-font text-white text-xs italic mt-8 ml-10 opacity-90 tracking-wider leading-relaxed max-w-[65%]" 
                        style={{ textShadow: '1px 1px 2px rgba(0,0,0,0.8)' }}
                      >
                        {mode.description}
                      </p>
                    </div>

                    {/* 3. RENDER LAYER */}
                    <img 
                      src={mode.icon_url} 
                      alt={mode.titre} 
                      className="absolute bottom-0 -right-4 h-[105%] w-auto object-contain z-20 drop-shadow-[0_10px_10px_rgba(0,0,0,0.4)] transition-all duration-500 char-card-render"
                      style={{ clipPath: 'inset(-100% -100% 0% -100%)', maxWidth: 'none' }}
                    />
                  </Link>
                </div>
              ))}
            </div>
          </section>

          {/* SECTION WORLD BOSS (EVENT BANNER STYLE) */}
          <section className="mb-16">
            <Link to="/game/world-boss/active/" className="block no-underline group">
              <div className="relative w-full h-[280px] bg-gradient-to-r from-red-950 to-black rounded-[3rem] overflow-hidden shadow-2xl border-4 border-red-600/20 group-hover:border-red-600/50 transition-all duration-500 flex items-center p-8 md:p-16">
                
                {/* Visual Background Decoration */}
                <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-20 mix-blend-overlay"></div>
                <div className="absolute top-0 right-0 w-1/2 h-full bg-gradient-to-l from-red-600/10 to-transparent"></div>

                <div className="relative z-10 max-w-2xl">
                  <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-red-600 text-white text-[10px] font-black uppercase tracking-widest mb-6 animate-pulse">
                    <span className="w-2 h-2 rounded-full bg-white"></span> EVENT EN COURS
                  </div>
                  <h2 className="text-4xl md:text-6xl font-black italic manga-font tracking-tighter uppercase text-white mb-4 leading-none">
                    WORLD <span className="text-red-600 text-glow">BOSS</span>
                  </h2>
                  <p className="text-sm md:text-lg font-bold text-white/60 uppercase tracking-[0.2em] leading-relaxed italic">
                    {isEn ? 'Join the global community to take down the legendary Titan.' : "Rejoignez la communauté mondiale pour terrasser le Titan légendaire."}
                  </p>
                </div>

                <img 
                  src="/static/img/modes/worldboss.png" 
                  className="absolute right-0 bottom-0 h-[110%] md:h-[130%] object-contain drop-shadow-[0_20px_50px_rgba(220,38,38,0.5)] group-hover:scale-110 group-hover:-rotate-3 transition-all duration-700 z-20 pointer-events-none" 
                  alt="World Boss" 
                />
              </div>
            </Link>
          </section>

          {/* SECTION MODES MULTI */}
          <section className="px-6 md:px-10 py-16 bg-gray-50 dark:bg-navy-900/30 rounded-[3rem] border border-black/5 dark:border-white/5 text-left">
            <h2 className="text-3xl font-black mb-12 flex items-baseline text-black dark:text-white uppercase italic manga-font">
              {isEn ? 'With Friends' : 'Entre Amis'}
              <span className="text-yellow-400 text-3xl leading-none ml-1">.</span>
            </h2>
            <div className="flex flex-wrap gap-12 justify-center pb-4">
              {modesMulti.map((mode) => (
                <Link 
                  key={mode.titre}
                  to={mode.url} 
                  className="collection-card rounded-3xl p-8 relative flex items-center justify-between w-full md:w-[500px] h-[220px] shadow-2xl transition-all duration-300 hover:scale-105 active:scale-95 no-underline group overflow-hidden border border-black/10"
                >
                  <div className="z-10 max-w-[60%]">
                    <h3 className="text-black text-4xl font-black italic tracking-tighter manga-font leading-none">{mode.titre}</h3>
                    <p className="text-white/80 text-xs font-bold uppercase tracking-widest mt-4 leading-relaxed">{mode.description}</p>
                  </div>
                  <img 
                    src={mode.icon_url} 
                    className="absolute -right-4 bottom-0 h-[220px] md:h-[240px] drop-shadow-lg transition-transform group-hover:scale-110 object-contain" 
                    alt={mode.titre} 
                  />
                </Link>
              ))}
            </div>
          </section>

          {/* SECTION CREATIVE (CINEMATIC BANNER STYLE) */}
          <section className="py-16 text-left">
            <h2 className="text-3xl font-black mb-12 flex items-baseline text-black dark:text-white uppercase italic manga-font">
              {isEn ? 'Creative Forge' : 'Créative'}
              <span className="text-yellow-400 text-4xl leading-none ml-1">.</span>
            </h2>
            
            {modesCreative.map((mode) => (
              <Link 
                key={mode.titre}
                to={mode.url} 
                className="w-full block no-underline group"
              >
                <div className="relative w-full h-[350px] md:h-[500px] bg-[#050505] rounded-[3rem] overflow-hidden shadow-2xl flex flex-col justify-between p-8 md:p-12 transition-transform duration-500 hover:scale-[1.01] active:scale-100">
                  
                  {/* FULL HEIGHT IMAGE (Behind the text bar) */}
                  <div className="absolute inset-0 w-full h-full flex items-center justify-center z-10 p-4">
                    <img 
                      src={mode.fusion_image} 
                      className="max-h-full max-w-full object-contain grayscale opacity-60 group-hover:grayscale-0 group-hover:opacity-100 group-hover:scale-105 transition-all duration-700" 
                      alt="Fusion" 
                    />
                  </div>

                  {/* Bottom Black Bar Overlay */}
                  <div className="absolute bottom-0 left-0 w-full h-[180px] bg-gradient-to-t from-black via-black/80 to-transparent z-20"></div>

                  {/* Footer Typography */}
                  <div className="relative z-30 mt-auto">
                    <h1 
                      className="text-white text-4xl md:text-7xl lg:text-9xl font-black uppercase tracking-tighter leading-none mb-3 manga-font italic" 
                      style={{ textShadow: '0 10px 30px rgba(0,0,0,0.5)' }}
                    >
                      {mode.titre}
                    </h1>
                    <p className="text-yellow-400 text-sm md:text-xl font-black uppercase tracking-[0.2em] manga-font opacity-90 leading-none">
                      {mode.titre_sub}
                    </p>
                  </div>
                </div>
              </Link>
            ))}
          </section>

          {/* SECTION EXPERIMENTAL (SINGULARITY LAB) */}
          <section className="py-24 text-center border-t border-black/5 dark:border-white/5">
              <div className="max-w-4xl mx-auto space-y-8">
                  <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-red-600/10 text-red-500 text-[10px] font-black uppercase tracking-widest mb-4">
                      <Zap className="w-3 h-3" /> NIVEAU OMEGA
                  </div>
                  <h2 className="text-5xl md:text-7xl font-black italic manga-font tracking-tighter uppercase text-black dark:text-white leading-none">
                      SINGULARITY <span className="text-red-600 text-glow">LABS</span>
                  </h2>
                  <p className="text-lg md:text-xl font-bold opacity-40 uppercase tracking-[0.3em] leading-relaxed italic">
                      {isEn ? 'Explore the boundaries of generative AI and pure cognition.' : "Explorez la frontière entre l'IA générative et la cognition pure."}
                  </p>
                  <Link 
                    to="/lab/" 
                    className="mt-12 group bg-black text-white hover:bg-red-600 py-6 px-16 rounded-[2rem] font-black italic text-xl uppercase shadow-2xl hover:scale-105 active:scale-95 transition-all inline-flex items-center gap-4 no-underline"
                  >
                    INITIALISER L'ACCÈS <ArrowRight className="w-6 h-6 group-hover:translate-x-2 transition-transform" />
                  </Link>
              </div>
          </section>
        </div>

    </div>
  );
}

export default App;
